/* This file is part of FineFramework project */
#ifndef FFW_GRAPHICS_GL_EXTENSIONS
#define FFW_GRAPHICS_GL_EXTENSIONS
#include "config.h"

#ifdef FFW_WINDOWS
#ifndef WINGDIAPI
#define FFW_WINGDIAPI_DEFINED 1
#define WINGDIAPI __declspec(dllimport)
#define APIENTRY _stdcall
#endif
#include <GL/gl.h>
#define GL_VERSION_1_0 1
#define GL_VERSION_1_1 1
#include "GL/glcorearb.h"
#endif

#ifdef FFW_LINUX
#include <GL/gl.h>
#define GL_VERSION_1_0 1
#define GL_VERSION_1_1 1
#include "GL/glcorearb.h"
#endif

#ifdef FFW_OSX
#define GL_DO_NOT_WARN_IF_MULTI_GL_VERSION_HEADERS_INCLUDED
#include <OpenGL/gl3.h>
#include <OpenGL/gl.h>
#define GL_VERSION_1_0 1
#define GL_VERSION_1_1 1
#include "GL/glcorearb.h"
#endif

namespace ffw {
    namespace gl {

#ifdef GL_VERSION_1_2
        extern FFW_API PFNGLCOPYTEXSUBIMAGE3DPROC CopyTexSubImage3D;
        extern FFW_API PFNGLDRAWRANGEELEMENTSPROC DrawRangeElements;
        extern FFW_API PFNGLTEXIMAGE3DPROC TexImage3D;
        extern FFW_API PFNGLTEXSUBIMAGE3DPROC TexSubImage3D;
#endif /* GL_VERSION_1_2 */

#ifdef GL_VERSION_1_3
        extern FFW_API PFNGLACTIVETEXTUREPROC ActiveTexture;
        extern FFW_API PFNGLCOMPRESSEDTEXIMAGE1DPROC CompressedTexImage1D;
        extern FFW_API PFNGLCOMPRESSEDTEXIMAGE2DPROC CompressedTexImage2D;
        extern FFW_API PFNGLCOMPRESSEDTEXIMAGE3DPROC CompressedTexImage3D;
        extern FFW_API PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC CompressedTexSubImage1D;
        extern FFW_API PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC CompressedTexSubImage2D;
        extern FFW_API PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC CompressedTexSubImage3D;
        extern FFW_API PFNGLGETCOMPRESSEDTEXIMAGEPROC GetCompressedTexImage;
        extern FFW_API PFNGLSAMPLECOVERAGEPROC SampleCoverage;
#endif /* GL_VERSION_1_3 */

#ifdef GL_VERSION_1_4
        extern FFW_API PFNGLBLENDCOLORPROC BlendColor;
        extern FFW_API PFNGLBLENDEQUATIONPROC BlendEquation;
        extern FFW_API PFNGLBLENDFUNCSEPARATEPROC BlendFuncSeparate;
        extern FFW_API PFNGLMULTIDRAWARRAYSPROC MultiDrawArrays;
        extern FFW_API PFNGLMULTIDRAWELEMENTSPROC MultiDrawElements;
        extern FFW_API PFNGLPOINTPARAMETERFPROC PointParameterf;
        extern FFW_API PFNGLPOINTPARAMETERFVPROC PointParameterfv;
        extern FFW_API PFNGLPOINTPARAMETERIPROC PointParameteri;
        extern FFW_API PFNGLPOINTPARAMETERIVPROC PointParameteriv;
#endif /* GL_VERSION_1_4 */

#ifdef GL_VERSION_1_5
        extern FFW_API PFNGLBEGINQUERYPROC BeginQuery;
        extern FFW_API PFNGLBINDBUFFERPROC BindBuffer;
        extern FFW_API PFNGLBUFFERDATAPROC BufferData;
        extern FFW_API PFNGLBUFFERSUBDATAPROC BufferSubData;
        extern FFW_API PFNGLDELETEBUFFERSPROC DeleteBuffers;
        extern FFW_API PFNGLDELETEQUERIESPROC DeleteQueries;
        extern FFW_API PFNGLENDQUERYPROC EndQuery;
        extern FFW_API PFNGLGENBUFFERSPROC GenBuffers;
        extern FFW_API PFNGLGENQUERIESPROC GenQueries;
        extern FFW_API PFNGLGETBUFFERPARAMETERIVPROC GetBufferParameteriv;
        extern FFW_API PFNGLGETBUFFERPOINTERVPROC GetBufferPointerv;
        extern FFW_API PFNGLGETBUFFERSUBDATAPROC GetBufferSubData;
        extern FFW_API PFNGLGETQUERYIVPROC GetQueryiv;
        extern FFW_API PFNGLGETQUERYOBJECTIVPROC GetQueryObjectiv;
        extern FFW_API PFNGLGETQUERYOBJECTUIVPROC GetQueryObjectuiv;
        extern FFW_API PFNGLISBUFFERPROC IsBuffer;
        extern FFW_API PFNGLISQUERYPROC IsQuery;
        extern FFW_API PFNGLMAPBUFFERPROC MapBuffer;
        extern FFW_API PFNGLUNMAPBUFFERPROC UnmapBuffer;
#endif /* GL_VERSION_1_5 */

#ifdef GL_VERSION_2_0
        extern FFW_API PFNGLATTACHSHADERPROC AttachShader;
        extern FFW_API PFNGLBINDATTRIBLOCATIONPROC BindAttribLocation;
        extern FFW_API PFNGLBLENDEQUATIONSEPARATEPROC BlendEquationSeparate;
        extern FFW_API PFNGLCOMPILESHADERPROC CompileShader;
        extern FFW_API PFNGLCREATEPROGRAMPROC CreateProgram;
        extern FFW_API PFNGLCREATESHADERPROC CreateShader;
        extern FFW_API PFNGLDELETEPROGRAMPROC DeleteProgram;
        extern FFW_API PFNGLDELETESHADERPROC DeleteShader;
        extern FFW_API PFNGLDETACHSHADERPROC DetachShader;
        extern FFW_API PFNGLDISABLEVERTEXATTRIBARRAYPROC DisableVertexAttribArray;
        extern FFW_API PFNGLDRAWBUFFERSPROC DrawBuffers;
        extern FFW_API PFNGLENABLEVERTEXATTRIBARRAYPROC EnableVertexAttribArray;
        extern FFW_API PFNGLGETACTIVEATTRIBPROC GetActiveAttrib;
        extern FFW_API PFNGLGETACTIVEUNIFORMPROC GetActiveUniform;
        extern FFW_API PFNGLGETATTACHEDSHADERSPROC GetAttachedShaders;
        extern FFW_API PFNGLGETATTRIBLOCATIONPROC GetAttribLocation;
        extern FFW_API PFNGLGETPROGRAMINFOLOGPROC GetProgramInfoLog;
        extern FFW_API PFNGLGETPROGRAMIVPROC GetProgramiv;
        extern FFW_API PFNGLGETSHADERINFOLOGPROC GetShaderInfoLog;
        extern FFW_API PFNGLGETSHADERIVPROC GetShaderiv;
        extern FFW_API PFNGLGETSHADERSOURCEPROC GetShaderSource;
        extern FFW_API PFNGLGETUNIFORMFVPROC GetUniformfv;
        extern FFW_API PFNGLGETUNIFORMIVPROC GetUniformiv;
        extern FFW_API PFNGLGETUNIFORMLOCATIONPROC GetUniformLocation;
        extern FFW_API PFNGLGETVERTEXATTRIBDVPROC GetVertexAttribdv;
        extern FFW_API PFNGLGETVERTEXATTRIBFVPROC GetVertexAttribfv;
        extern FFW_API PFNGLGETVERTEXATTRIBIVPROC GetVertexAttribiv;
        extern FFW_API PFNGLGETVERTEXATTRIBPOINTERVPROC GetVertexAttribPointerv;
        extern FFW_API PFNGLISPROGRAMPROC IsProgram;
        extern FFW_API PFNGLISSHADERPROC IsShader;
        extern FFW_API PFNGLLINKPROGRAMPROC LinkProgram;
        extern FFW_API PFNGLSHADERSOURCEPROC ShaderSource;
        extern FFW_API PFNGLSTENCILFUNCSEPARATEPROC StencilFuncSeparate;
        extern FFW_API PFNGLSTENCILMASKSEPARATEPROC StencilMaskSeparate;
        extern FFW_API PFNGLSTENCILOPSEPARATEPROC StencilOpSeparate;
        extern FFW_API PFNGLUNIFORM1FPROC Uniform1f;
        extern FFW_API PFNGLUNIFORM1FVPROC Uniform1fv;
        extern FFW_API PFNGLUNIFORM1IPROC Uniform1i;
        extern FFW_API PFNGLUNIFORM1IVPROC Uniform1iv;
        extern FFW_API PFNGLUNIFORM2FPROC Uniform2f;
        extern FFW_API PFNGLUNIFORM2FVPROC Uniform2fv;
        extern FFW_API PFNGLUNIFORM2IPROC Uniform2i;
        extern FFW_API PFNGLUNIFORM2IVPROC Uniform2iv;
        extern FFW_API PFNGLUNIFORM3FPROC Uniform3f;
        extern FFW_API PFNGLUNIFORM3FVPROC Uniform3fv;
        extern FFW_API PFNGLUNIFORM3IPROC Uniform3i;
        extern FFW_API PFNGLUNIFORM3IVPROC Uniform3iv;
        extern FFW_API PFNGLUNIFORM4FPROC Uniform4f;
        extern FFW_API PFNGLUNIFORM4FVPROC Uniform4fv;
        extern FFW_API PFNGLUNIFORM4IPROC Uniform4i;
        extern FFW_API PFNGLUNIFORM4IVPROC Uniform4iv;
        extern FFW_API PFNGLUNIFORMMATRIX2FVPROC UniformMatrix2fv;
        extern FFW_API PFNGLUNIFORMMATRIX3FVPROC UniformMatrix3fv;
        extern FFW_API PFNGLUNIFORMMATRIX4FVPROC UniformMatrix4fv;
        extern FFW_API PFNGLUSEPROGRAMPROC UseProgram;
        extern FFW_API PFNGLVALIDATEPROGRAMPROC ValidateProgram;
        extern FFW_API PFNGLVERTEXATTRIB1DPROC VertexAttrib1d;
        extern FFW_API PFNGLVERTEXATTRIB1DVPROC VertexAttrib1dv;
        extern FFW_API PFNGLVERTEXATTRIB1FPROC VertexAttrib1f;
        extern FFW_API PFNGLVERTEXATTRIB1FVPROC VertexAttrib1fv;
        extern FFW_API PFNGLVERTEXATTRIB1SPROC VertexAttrib1s;
        extern FFW_API PFNGLVERTEXATTRIB1SVPROC VertexAttrib1sv;
        extern FFW_API PFNGLVERTEXATTRIB2DPROC VertexAttrib2d;
        extern FFW_API PFNGLVERTEXATTRIB2DVPROC VertexAttrib2dv;
        extern FFW_API PFNGLVERTEXATTRIB2FPROC VertexAttrib2f;
        extern FFW_API PFNGLVERTEXATTRIB2FVPROC VertexAttrib2fv;
        extern FFW_API PFNGLVERTEXATTRIB2SPROC VertexAttrib2s;
        extern FFW_API PFNGLVERTEXATTRIB2SVPROC VertexAttrib2sv;
        extern FFW_API PFNGLVERTEXATTRIB3DPROC VertexAttrib3d;
        extern FFW_API PFNGLVERTEXATTRIB3DVPROC VertexAttrib3dv;
        extern FFW_API PFNGLVERTEXATTRIB3FPROC VertexAttrib3f;
        extern FFW_API PFNGLVERTEXATTRIB3FVPROC VertexAttrib3fv;
        extern FFW_API PFNGLVERTEXATTRIB3SPROC VertexAttrib3s;
        extern FFW_API PFNGLVERTEXATTRIB3SVPROC VertexAttrib3sv;
        extern FFW_API PFNGLVERTEXATTRIB4BVPROC VertexAttrib4bv;
        extern FFW_API PFNGLVERTEXATTRIB4DPROC VertexAttrib4d;
        extern FFW_API PFNGLVERTEXATTRIB4DVPROC VertexAttrib4dv;
        extern FFW_API PFNGLVERTEXATTRIB4FPROC VertexAttrib4f;
        extern FFW_API PFNGLVERTEXATTRIB4FVPROC VertexAttrib4fv;
        extern FFW_API PFNGLVERTEXATTRIB4IVPROC VertexAttrib4iv;
        extern FFW_API PFNGLVERTEXATTRIB4NBVPROC VertexAttrib4Nbv;
        extern FFW_API PFNGLVERTEXATTRIB4NIVPROC VertexAttrib4Niv;
        extern FFW_API PFNGLVERTEXATTRIB4NSVPROC VertexAttrib4Nsv;
        extern FFW_API PFNGLVERTEXATTRIB4NUBPROC VertexAttrib4Nub;
        extern FFW_API PFNGLVERTEXATTRIB4NUBVPROC VertexAttrib4Nubv;
        extern FFW_API PFNGLVERTEXATTRIB4NUIVPROC VertexAttrib4Nuiv;
        extern FFW_API PFNGLVERTEXATTRIB4NUSVPROC VertexAttrib4Nusv;
        extern FFW_API PFNGLVERTEXATTRIB4SPROC VertexAttrib4s;
        extern FFW_API PFNGLVERTEXATTRIB4SVPROC VertexAttrib4sv;
        extern FFW_API PFNGLVERTEXATTRIB4UBVPROC VertexAttrib4ubv;
        extern FFW_API PFNGLVERTEXATTRIB4UIVPROC VertexAttrib4uiv;
        extern FFW_API PFNGLVERTEXATTRIB4USVPROC VertexAttrib4usv;
        extern FFW_API PFNGLVERTEXATTRIBPOINTERPROC VertexAttribPointer;
#endif /* GL_VERSION_2_0 */

#ifdef GL_VERSION_2_1
        extern FFW_API PFNGLUNIFORMMATRIX2X3FVPROC UniformMatrix2x3fv;
        extern FFW_API PFNGLUNIFORMMATRIX2X4FVPROC UniformMatrix2x4fv;
        extern FFW_API PFNGLUNIFORMMATRIX3X2FVPROC UniformMatrix3x2fv;
        extern FFW_API PFNGLUNIFORMMATRIX3X4FVPROC UniformMatrix3x4fv;
        extern FFW_API PFNGLUNIFORMMATRIX4X2FVPROC UniformMatrix4x2fv;
        extern FFW_API PFNGLUNIFORMMATRIX4X3FVPROC UniformMatrix4x3fv;
#endif /* GL_VERSION_2_1 */

#ifdef GL_VERSION_3_0
        extern FFW_API PFNGLBEGINCONDITIONALRENDERPROC BeginConditionalRender;
        extern FFW_API PFNGLBEGINTRANSFORMFEEDBACKPROC BeginTransformFeedback;
        extern FFW_API PFNGLBINDBUFFERBASEPROC BindBufferBase;
        extern FFW_API PFNGLBINDBUFFERRANGEPROC BindBufferRange;
        extern FFW_API PFNGLBINDFRAGDATALOCATIONPROC BindFragDataLocation;
        extern FFW_API PFNGLBINDFRAMEBUFFERPROC BindFramebuffer;
        extern FFW_API PFNGLBINDRENDERBUFFERPROC BindRenderbuffer;
        extern FFW_API PFNGLBINDVERTEXARRAYPROC BindVertexArray;
        extern FFW_API PFNGLBLITFRAMEBUFFERPROC BlitFramebuffer;
        extern FFW_API PFNGLCHECKFRAMEBUFFERSTATUSPROC CheckFramebufferStatus;
        extern FFW_API PFNGLCLAMPCOLORPROC ClampColor;
        extern FFW_API PFNGLCLEARBUFFERFIPROC ClearBufferfi;
        extern FFW_API PFNGLCLEARBUFFERFVPROC ClearBufferfv;
        extern FFW_API PFNGLCLEARBUFFERIVPROC ClearBufferiv;
        extern FFW_API PFNGLCLEARBUFFERUIVPROC ClearBufferuiv;
        extern FFW_API PFNGLCOLORMASKIPROC ColorMaski;
        extern FFW_API PFNGLDELETEFRAMEBUFFERSPROC DeleteFramebuffers;
        extern FFW_API PFNGLDELETERENDERBUFFERSPROC DeleteRenderbuffers;
        extern FFW_API PFNGLDELETEVERTEXARRAYSPROC DeleteVertexArrays;
        extern FFW_API PFNGLDISABLEIPROC Disablei;
        extern FFW_API PFNGLENABLEIPROC Enablei;
        extern FFW_API PFNGLENDCONDITIONALRENDERPROC EndConditionalRender;
        extern FFW_API PFNGLENDTRANSFORMFEEDBACKPROC EndTransformFeedback;
        extern FFW_API PFNGLFLUSHMAPPEDBUFFERRANGEPROC FlushMappedBufferRange;
        extern FFW_API PFNGLFRAMEBUFFERRENDERBUFFERPROC FramebufferRenderbuffer;
        extern FFW_API PFNGLFRAMEBUFFERTEXTURE1DPROC FramebufferTexture1D;
        extern FFW_API PFNGLFRAMEBUFFERTEXTURE2DPROC FramebufferTexture2D;
        extern FFW_API PFNGLFRAMEBUFFERTEXTURE3DPROC FramebufferTexture3D;
        extern FFW_API PFNGLFRAMEBUFFERTEXTURELAYERPROC FramebufferTextureLayer;
        extern FFW_API PFNGLGENERATEMIPMAPPROC GenerateMipmap;
        extern FFW_API PFNGLGENFRAMEBUFFERSPROC GenFramebuffers;
        extern FFW_API PFNGLGENRENDERBUFFERSPROC GenRenderbuffers;
        extern FFW_API PFNGLGENVERTEXARRAYSPROC GenVertexArrays;
        extern FFW_API PFNGLGETBOOLEANI_VPROC GetBooleani_v;
        extern FFW_API PFNGLGETFRAGDATALOCATIONPROC GetFragDataLocation;
        extern FFW_API PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC GetFramebufferAttachmentParameteriv;
        extern FFW_API PFNGLGETINTEGERI_VPROC GetIntegeri_v;
        extern FFW_API PFNGLGETRENDERBUFFERPARAMETERIVPROC GetRenderbufferParameteriv;
        extern FFW_API PFNGLGETSTRINGIPROC GetStringi;
        extern FFW_API PFNGLGETTEXPARAMETERIIVPROC GetTexParameterIiv;
        extern FFW_API PFNGLGETTEXPARAMETERIUIVPROC GetTexParameterIuiv;
        extern FFW_API PFNGLGETTRANSFORMFEEDBACKVARYINGPROC GetTransformFeedbackVarying;
        extern FFW_API PFNGLGETUNIFORMUIVPROC GetUniformuiv;
        extern FFW_API PFNGLGETVERTEXATTRIBIIVPROC GetVertexAttribIiv;
        extern FFW_API PFNGLGETVERTEXATTRIBIUIVPROC GetVertexAttribIuiv;
        extern FFW_API PFNGLISENABLEDIPROC IsEnabledi;
        extern FFW_API PFNGLISFRAMEBUFFERPROC IsFramebuffer;
        extern FFW_API PFNGLISRENDERBUFFERPROC IsRenderbuffer;
        extern FFW_API PFNGLISVERTEXARRAYPROC IsVertexArray;
        extern FFW_API PFNGLMAPBUFFERRANGEPROC MapBufferRange;
        extern FFW_API PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC RenderbufferStorageMultisample;
        extern FFW_API PFNGLRENDERBUFFERSTORAGEPROC RenderbufferStorage;
        extern FFW_API PFNGLTEXPARAMETERIIVPROC TexParameterIiv;
        extern FFW_API PFNGLTEXPARAMETERIUIVPROC TexParameterIuiv;
        extern FFW_API PFNGLTRANSFORMFEEDBACKVARYINGSPROC TransformFeedbackVaryings;
        extern FFW_API PFNGLUNIFORM1UIPROC Uniform1ui;
        extern FFW_API PFNGLUNIFORM1UIVPROC Uniform1uiv;
        extern FFW_API PFNGLUNIFORM2UIPROC Uniform2ui;
        extern FFW_API PFNGLUNIFORM2UIVPROC Uniform2uiv;
        extern FFW_API PFNGLUNIFORM3UIPROC Uniform3ui;
        extern FFW_API PFNGLUNIFORM3UIVPROC Uniform3uiv;
        extern FFW_API PFNGLUNIFORM4UIPROC Uniform4ui;
        extern FFW_API PFNGLUNIFORM4UIVPROC Uniform4uiv;
        extern FFW_API PFNGLVERTEXATTRIBI1IPROC VertexAttribI1i;
        extern FFW_API PFNGLVERTEXATTRIBI1IVPROC VertexAttribI1iv;
        extern FFW_API PFNGLVERTEXATTRIBI1UIPROC VertexAttribI1ui;
        extern FFW_API PFNGLVERTEXATTRIBI1UIVPROC VertexAttribI1uiv;
        extern FFW_API PFNGLVERTEXATTRIBI2IPROC VertexAttribI2i;
        extern FFW_API PFNGLVERTEXATTRIBI2IVPROC VertexAttribI2iv;
        extern FFW_API PFNGLVERTEXATTRIBI2UIPROC VertexAttribI2ui;
        extern FFW_API PFNGLVERTEXATTRIBI2UIVPROC VertexAttribI2uiv;
        extern FFW_API PFNGLVERTEXATTRIBI3IPROC VertexAttribI3i;
        extern FFW_API PFNGLVERTEXATTRIBI3IVPROC VertexAttribI3iv;
        extern FFW_API PFNGLVERTEXATTRIBI3UIPROC VertexAttribI3ui;
        extern FFW_API PFNGLVERTEXATTRIBI3UIVPROC VertexAttribI3uiv;
        extern FFW_API PFNGLVERTEXATTRIBI4BVPROC VertexAttribI4bv;
        extern FFW_API PFNGLVERTEXATTRIBI4IPROC VertexAttribI4i;
        extern FFW_API PFNGLVERTEXATTRIBI4IVPROC VertexAttribI4iv;
        extern FFW_API PFNGLVERTEXATTRIBI4SVPROC VertexAttribI4sv;
        extern FFW_API PFNGLVERTEXATTRIBI4UBVPROC VertexAttribI4ubv;
        extern FFW_API PFNGLVERTEXATTRIBI4UIPROC VertexAttribI4ui;
        extern FFW_API PFNGLVERTEXATTRIBI4UIVPROC VertexAttribI4uiv;
        extern FFW_API PFNGLVERTEXATTRIBI4USVPROC VertexAttribI4usv;
        extern FFW_API PFNGLVERTEXATTRIBIPOINTERPROC VertexAttribIPointer;
#endif /* GL_VERSION_3_0 */

#ifdef GL_VERSION_3_1
        extern FFW_API PFNGLCOPYBUFFERSUBDATAPROC CopyBufferSubData;
        extern FFW_API PFNGLDRAWARRAYSINSTANCEDPROC DrawArraysInstanced;
        extern FFW_API PFNGLDRAWELEMENTSINSTANCEDPROC DrawElementsInstanced;
        extern FFW_API PFNGLGETACTIVEUNIFORMBLOCKIVPROC GetActiveUniformBlockiv;
        extern FFW_API PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC GetActiveUniformBlockName;
        extern FFW_API PFNGLGETACTIVEUNIFORMNAMEPROC GetActiveUniformName;
        extern FFW_API PFNGLGETACTIVEUNIFORMSIVPROC GetActiveUniformsiv;
        extern FFW_API PFNGLGETUNIFORMBLOCKINDEXPROC GetUniformBlockIndex;
        extern FFW_API PFNGLGETUNIFORMINDICESPROC GetUniformIndices;
        extern FFW_API PFNGLPRIMITIVERESTARTINDEXPROC PrimitiveRestartIndex;
        extern FFW_API PFNGLTEXBUFFERPROC TexBuffer;
        extern FFW_API PFNGLUNIFORMBLOCKBINDINGPROC UniformBlockBinding;
#endif /* GL_VERSION_3_1 */

#ifdef GL_VERSION_3_2
        extern FFW_API PFNGLCLIENTWAITSYNCPROC ClientWaitSync;
        extern FFW_API PFNGLDELETESYNCPROC DeleteSync;
        extern FFW_API PFNGLDRAWELEMENTSBASEVERTEXPROC DrawElementsBaseVertex;
        extern FFW_API PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC DrawElementsInstancedBaseVertex;
        extern FFW_API PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC DrawRangeElementsBaseVertex;
        extern FFW_API PFNGLFENCESYNCPROC FenceSync;
        extern FFW_API PFNGLFRAMEBUFFERTEXTUREPROC FramebufferTexture;
        extern FFW_API PFNGLGETBUFFERPARAMETERI64VPROC GetBufferParameteri64v;
        extern FFW_API PFNGLGETINTEGER64I_VPROC GetInteger64i_v;
        extern FFW_API PFNGLGETINTEGER64VPROC GetInteger64v;
        extern FFW_API PFNGLGETMULTISAMPLEFVPROC GetMultisamplefv;
        extern FFW_API PFNGLGETSYNCIVPROC GetSynciv;
        extern FFW_API PFNGLISSYNCPROC IsSync;
        extern FFW_API PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC MultiDrawElementsBaseVertex;
        extern FFW_API PFNGLPROVOKINGVERTEXPROC ProvokingVertex;
        extern FFW_API PFNGLSAMPLEMASKIPROC SampleMaski;
        extern FFW_API PFNGLTEXIMAGE2DMULTISAMPLEPROC TexImage2DMultisample;
        extern FFW_API PFNGLTEXIMAGE3DMULTISAMPLEPROC TexImage3DMultisample;
        extern FFW_API PFNGLWAITSYNCPROC WaitSync;
#endif /* GL_VERSION_3_2 */

#ifdef GL_VERSION_3_3
        extern FFW_API PFNGLBINDFRAGDATALOCATIONINDEXEDPROC BindFragDataLocationIndexed;
        extern FFW_API PFNGLBINDSAMPLERPROC BindSampler;
        extern FFW_API PFNGLDELETESAMPLERSPROC DeleteSamplers;
        extern FFW_API PFNGLGENSAMPLERSPROC GenSamplers;
        extern FFW_API PFNGLGETFRAGDATAINDEXPROC GetFragDataIndex;
        extern FFW_API PFNGLGETQUERYOBJECTI64VPROC GetQueryObjecti64v;
        extern FFW_API PFNGLGETQUERYOBJECTUI64VPROC GetQueryObjectui64v;
        extern FFW_API PFNGLGETSAMPLERPARAMETERFVPROC GetSamplerParameterfv;
        extern FFW_API PFNGLGETSAMPLERPARAMETERIIVPROC GetSamplerParameterIiv;
        extern FFW_API PFNGLGETSAMPLERPARAMETERIUIVPROC GetSamplerParameterIuiv;
        extern FFW_API PFNGLGETSAMPLERPARAMETERIVPROC GetSamplerParameteriv;
        extern FFW_API PFNGLISSAMPLERPROC IsSampler;
        extern FFW_API PFNGLQUERYCOUNTERPROC QueryCounter;
        extern FFW_API PFNGLSAMPLERPARAMETERFPROC SamplerParameterf;
        extern FFW_API PFNGLSAMPLERPARAMETERFVPROC SamplerParameterfv;
        extern FFW_API PFNGLSAMPLERPARAMETERIIVPROC SamplerParameterIiv;
        extern FFW_API PFNGLSAMPLERPARAMETERIPROC SamplerParameteri;
        extern FFW_API PFNGLSAMPLERPARAMETERIUIVPROC SamplerParameterIuiv;
        extern FFW_API PFNGLSAMPLERPARAMETERIVPROC SamplerParameteriv;
        extern FFW_API PFNGLVERTEXATTRIBDIVISORPROC VertexAttribDivisor;
        extern FFW_API PFNGLVERTEXATTRIBP1UIPROC VertexAttribP1ui;
        extern FFW_API PFNGLVERTEXATTRIBP1UIVPROC VertexAttribP1uiv;
        extern FFW_API PFNGLVERTEXATTRIBP2UIPROC VertexAttribP2ui;
        extern FFW_API PFNGLVERTEXATTRIBP2UIVPROC VertexAttribP2uiv;
        extern FFW_API PFNGLVERTEXATTRIBP3UIPROC VertexAttribP3ui;
        extern FFW_API PFNGLVERTEXATTRIBP3UIVPROC VertexAttribP3uiv;
        extern FFW_API PFNGLVERTEXATTRIBP4UIPROC VertexAttribP4ui;
        extern FFW_API PFNGLVERTEXATTRIBP4UIVPROC VertexAttribP4uiv;
#endif /* GL_VERSION_3_3 */

#ifdef GL_VERSION_4_0
        extern FFW_API PFNGLBEGINQUERYINDEXEDPROC BeginQueryIndexed;
        extern FFW_API PFNGLBINDTRANSFORMFEEDBACKPROC BindTransformFeedback;
        extern FFW_API PFNGLBLENDEQUATIONIPROC BlendEquationi;
        extern FFW_API PFNGLBLENDEQUATIONSEPARATEIPROC BlendEquationSeparatei;
        extern FFW_API PFNGLBLENDFUNCIPROC BlendFunci;
        extern FFW_API PFNGLBLENDFUNCSEPARATEIPROC BlendFuncSeparatei;
        extern FFW_API PFNGLDELETETRANSFORMFEEDBACKSPROC DeleteTransformFeedbacks;
        extern FFW_API PFNGLDRAWARRAYSINDIRECTPROC DrawArraysIndirect;
        extern FFW_API PFNGLDRAWELEMENTSINDIRECTPROC DrawElementsIndirect;
        extern FFW_API PFNGLDRAWTRANSFORMFEEDBACKPROC DrawTransformFeedback;
        extern FFW_API PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC DrawTransformFeedbackStream;
        extern FFW_API PFNGLENDQUERYINDEXEDPROC EndQueryIndexed;
        extern FFW_API PFNGLGENTRANSFORMFEEDBACKSPROC GenTransformFeedbacks;
        extern FFW_API PFNGLGETACTIVESUBROUTINENAMEPROC GetActiveSubroutineName;
        extern FFW_API PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC GetActiveSubroutineUniformiv;
        extern FFW_API PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC GetActiveSubroutineUniformName;
        extern FFW_API PFNGLGETPROGRAMSTAGEIVPROC GetProgramStageiv;
        extern FFW_API PFNGLGETQUERYINDEXEDIVPROC GetQueryIndexediv;
        extern FFW_API PFNGLGETSUBROUTINEINDEXPROC GetSubroutineIndex;
        extern FFW_API PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC GetSubroutineUniformLocation;
        extern FFW_API PFNGLGETUNIFORMDVPROC GetUniformdv;
        extern FFW_API PFNGLGETUNIFORMSUBROUTINEUIVPROC GetUniformSubroutineuiv;
        extern FFW_API PFNGLISTRANSFORMFEEDBACKPROC IsTransformFeedback;
        extern FFW_API PFNGLMINSAMPLESHADINGPROC MinSampleShading;
        extern FFW_API PFNGLPATCHPARAMETERFVPROC PatchParameterfv;
        extern FFW_API PFNGLPATCHPARAMETERIPROC PatchParameteri;
        extern FFW_API PFNGLPAUSETRANSFORMFEEDBACKPROC PauseTransformFeedback;
        extern FFW_API PFNGLRESUMETRANSFORMFEEDBACKPROC ResumeTransformFeedback;
        extern FFW_API PFNGLUNIFORM1DPROC Uniform1d;
        extern FFW_API PFNGLUNIFORM1DVPROC Uniform1dv;
        extern FFW_API PFNGLUNIFORM2DPROC Uniform2d;
        extern FFW_API PFNGLUNIFORM2DVPROC Uniform2dv;
        extern FFW_API PFNGLUNIFORM3DPROC Uniform3d;
        extern FFW_API PFNGLUNIFORM3DVPROC Uniform3dv;
        extern FFW_API PFNGLUNIFORM4DPROC Uniform4d;
        extern FFW_API PFNGLUNIFORM4DVPROC Uniform4dv;
        extern FFW_API PFNGLUNIFORMMATRIX2DVPROC UniformMatrix2dv;
        extern FFW_API PFNGLUNIFORMMATRIX2X3DVPROC UniformMatrix2x3dv;
        extern FFW_API PFNGLUNIFORMMATRIX2X4DVPROC UniformMatrix2x4dv;
        extern FFW_API PFNGLUNIFORMMATRIX3DVPROC UniformMatrix3dv;
        extern FFW_API PFNGLUNIFORMMATRIX3X2DVPROC UniformMatrix3x2dv;
        extern FFW_API PFNGLUNIFORMMATRIX3X4DVPROC UniformMatrix3x4dv;
        extern FFW_API PFNGLUNIFORMMATRIX4DVPROC UniformMatrix4dv;
        extern FFW_API PFNGLUNIFORMMATRIX4X2DVPROC UniformMatrix4x2dv;
        extern FFW_API PFNGLUNIFORMMATRIX4X3DVPROC UniformMatrix4x3dv;
        extern FFW_API PFNGLUNIFORMSUBROUTINESUIVPROC UniformSubroutinesuiv;
#endif /* GL_VERSION_4_0 */

#ifdef GL_VERSION_4_1
        extern FFW_API PFNGLACTIVESHADERPROGRAMPROC ActiveShaderProgram;
        extern FFW_API PFNGLBINDPROGRAMPIPELINEPROC BindProgramPipeline;
        extern FFW_API PFNGLCLEARDEPTHFPROC ClearDepthf;
        extern FFW_API PFNGLCREATESHADERPROGRAMVPROC CreateShaderProgramv;
        extern FFW_API PFNGLDELETEPROGRAMPIPELINESPROC DeleteProgramPipelines;
        extern FFW_API PFNGLDEPTHRANGEARRAYVPROC DepthRangeArrayv;
        extern FFW_API PFNGLDEPTHRANGEFPROC DepthRangef;
        extern FFW_API PFNGLDEPTHRANGEINDEXEDPROC DepthRangeIndexed;
        extern FFW_API PFNGLGENPROGRAMPIPELINESPROC GenProgramPipelines;
        extern FFW_API PFNGLGETDOUBLEI_VPROC GetDoublei_v;
        extern FFW_API PFNGLGETFLOATI_VPROC GetFloati_v;
        extern FFW_API PFNGLGETPROGRAMBINARYPROC GetProgramBinary;
        extern FFW_API PFNGLGETPROGRAMPIPELINEINFOLOGPROC GetProgramPipelineInfoLog;
        extern FFW_API PFNGLGETPROGRAMPIPELINEIVPROC GetProgramPipelineiv;
        extern FFW_API PFNGLGETSHADERPRECISIONFORMATPROC GetShaderPrecisionFormat;
        extern FFW_API PFNGLGETVERTEXATTRIBLDVPROC GetVertexAttribLdv;
        extern FFW_API PFNGLISPROGRAMPIPELINEPROC IsProgramPipeline;
        extern FFW_API PFNGLPROGRAMBINARYPROC ProgramBinary;
        extern FFW_API PFNGLPROGRAMPARAMETERIPROC ProgramParameteri;
        extern FFW_API PFNGLPROGRAMUNIFORM1DPROC ProgramUniform1d;
        extern FFW_API PFNGLPROGRAMUNIFORM1DVPROC ProgramUniform1dv;
        extern FFW_API PFNGLPROGRAMUNIFORM1FPROC ProgramUniform1f;
        extern FFW_API PFNGLPROGRAMUNIFORM1FVPROC ProgramUniform1fv;
        extern FFW_API PFNGLPROGRAMUNIFORM1IPROC ProgramUniform1i;
        extern FFW_API PFNGLPROGRAMUNIFORM1IVPROC ProgramUniform1iv;
        extern FFW_API PFNGLPROGRAMUNIFORM1UIPROC ProgramUniform1ui;
        extern FFW_API PFNGLPROGRAMUNIFORM1UIVPROC ProgramUniform1uiv;
        extern FFW_API PFNGLPROGRAMUNIFORM2DPROC ProgramUniform2d;
        extern FFW_API PFNGLPROGRAMUNIFORM2DVPROC ProgramUniform2dv;
        extern FFW_API PFNGLPROGRAMUNIFORM2FPROC ProgramUniform2f;
        extern FFW_API PFNGLPROGRAMUNIFORM2FVPROC ProgramUniform2fv;
        extern FFW_API PFNGLPROGRAMUNIFORM2IPROC ProgramUniform2i;
        extern FFW_API PFNGLPROGRAMUNIFORM2IVPROC ProgramUniform2iv;
        extern FFW_API PFNGLPROGRAMUNIFORM2UIPROC ProgramUniform2ui;
        extern FFW_API PFNGLPROGRAMUNIFORM2UIVPROC ProgramUniform2uiv;
        extern FFW_API PFNGLPROGRAMUNIFORM3DPROC ProgramUniform3d;
        extern FFW_API PFNGLPROGRAMUNIFORM3DVPROC ProgramUniform3dv;
        extern FFW_API PFNGLPROGRAMUNIFORM3FPROC ProgramUniform3f;
        extern FFW_API PFNGLPROGRAMUNIFORM3FVPROC ProgramUniform3fv;
        extern FFW_API PFNGLPROGRAMUNIFORM3IPROC ProgramUniform3i;
        extern FFW_API PFNGLPROGRAMUNIFORM3IVPROC ProgramUniform3iv;
        extern FFW_API PFNGLPROGRAMUNIFORM3UIPROC ProgramUniform3ui;
        extern FFW_API PFNGLPROGRAMUNIFORM3UIVPROC ProgramUniform3uiv;
        extern FFW_API PFNGLPROGRAMUNIFORM4DPROC ProgramUniform4d;
        extern FFW_API PFNGLPROGRAMUNIFORM4DVPROC ProgramUniform4dv;
        extern FFW_API PFNGLPROGRAMUNIFORM4FPROC ProgramUniform4f;
        extern FFW_API PFNGLPROGRAMUNIFORM4FVPROC ProgramUniform4fv;
        extern FFW_API PFNGLPROGRAMUNIFORM4IPROC ProgramUniform4i;
        extern FFW_API PFNGLPROGRAMUNIFORM4IVPROC ProgramUniform4iv;
        extern FFW_API PFNGLPROGRAMUNIFORM4UIPROC ProgramUniform4ui;
        extern FFW_API PFNGLPROGRAMUNIFORM4UIVPROC ProgramUniform4uiv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX2DVPROC ProgramUniformMatrix2dv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX2FVPROC ProgramUniformMatrix2fv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC ProgramUniformMatrix2x3dv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC ProgramUniformMatrix2x3fv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC ProgramUniformMatrix2x4dv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC ProgramUniformMatrix2x4fv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX3DVPROC ProgramUniformMatrix3dv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX3FVPROC ProgramUniformMatrix3fv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC ProgramUniformMatrix3x2dv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC ProgramUniformMatrix3x2fv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC ProgramUniformMatrix3x4dv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC ProgramUniformMatrix3x4fv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX4DVPROC ProgramUniformMatrix4dv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX4FVPROC ProgramUniformMatrix4fv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC ProgramUniformMatrix4x2dv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC ProgramUniformMatrix4x2fv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC ProgramUniformMatrix4x3dv;
        extern FFW_API PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC ProgramUniformMatrix4x3fv;
        extern FFW_API PFNGLRELEASESHADERCOMPILERPROC ReleaseShaderCompiler;
        extern FFW_API PFNGLSCISSORARRAYVPROC ScissorArrayv;
        extern FFW_API PFNGLSCISSORINDEXEDPROC ScissorIndexed;
        extern FFW_API PFNGLSCISSORINDEXEDVPROC ScissorIndexedv;
        extern FFW_API PFNGLSHADERBINARYPROC ShaderBinary;
        extern FFW_API PFNGLUSEPROGRAMSTAGESPROC UseProgramStages;
        extern FFW_API PFNGLVALIDATEPROGRAMPIPELINEPROC ValidateProgramPipeline;
        extern FFW_API PFNGLVERTEXATTRIBL1DPROC VertexAttribL1d;
        extern FFW_API PFNGLVERTEXATTRIBL1DVPROC VertexAttribL1dv;
        extern FFW_API PFNGLVERTEXATTRIBL2DPROC VertexAttribL2d;
        extern FFW_API PFNGLVERTEXATTRIBL2DVPROC VertexAttribL2dv;
        extern FFW_API PFNGLVERTEXATTRIBL3DPROC VertexAttribL3d;
        extern FFW_API PFNGLVERTEXATTRIBL3DVPROC VertexAttribL3dv;
        extern FFW_API PFNGLVERTEXATTRIBL4DPROC VertexAttribL4d;
        extern FFW_API PFNGLVERTEXATTRIBL4DVPROC VertexAttribL4dv;
        extern FFW_API PFNGLVERTEXATTRIBLPOINTERPROC VertexAttribLPointer;
        extern FFW_API PFNGLVIEWPORTARRAYVPROC ViewportArrayv;
        extern FFW_API PFNGLVIEWPORTINDEXEDFPROC ViewportIndexedf;
        extern FFW_API PFNGLVIEWPORTINDEXEDFVPROC ViewportIndexedfv;
#endif /* GL_VERSION_4_1 */

#ifdef GL_VERSION_4_2
        extern FFW_API PFNGLBINDIMAGETEXTUREPROC BindImageTexture;
        extern FFW_API PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC DrawArraysInstancedBaseInstance;
        extern FFW_API PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC DrawElementsInstancedBaseInstance;
        extern FFW_API PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC DrawElementsInstancedBaseVertexBaseInstance;
        extern FFW_API PFNGLDRAWTRANSFORMFEEDBACKINSTANCEDPROC DrawTransformFeedbackInstanced;
        extern FFW_API PFNGLDRAWTRANSFORMFEEDBACKSTREAMINSTANCEDPROC DrawTransformFeedbackStreamInstanced;
        extern FFW_API PFNGLGETACTIVEATOMICCOUNTERBUFFERIVPROC GetActiveAtomicCounterBufferiv;
        extern FFW_API PFNGLGETINTERNALFORMATIVPROC GetInternalformativ;
        extern FFW_API PFNGLMEMORYBARRIERPROC MemoryBarrier;
        extern FFW_API PFNGLTEXSTORAGE1DPROC TexStorage1D;
        extern FFW_API PFNGLTEXSTORAGE2DPROC TexStorage2D;
        extern FFW_API PFNGLTEXSTORAGE3DPROC TexStorage3D;
#endif /* GL_VERSION_4_2 */

#ifdef GL_VERSION_4_3
        extern FFW_API PFNGLBINDVERTEXBUFFERPROC BindVertexBuffer;
        extern FFW_API PFNGLCLEARBUFFERDATAPROC ClearBufferData;
        extern FFW_API PFNGLCLEARBUFFERSUBDATAPROC ClearBufferSubData;
        extern FFW_API PFNGLCOPYIMAGESUBDATAPROC CopyImageSubData;
        extern FFW_API PFNGLDEBUGMESSAGECALLBACKPROC DebugMessageCallback;
        extern FFW_API PFNGLDEBUGMESSAGECONTROLPROC DebugMessageControl;
        extern FFW_API PFNGLDEBUGMESSAGEINSERTPROC DebugMessageInsert;
        extern FFW_API PFNGLDISPATCHCOMPUTEINDIRECTPROC DispatchComputeIndirect;
        extern FFW_API PFNGLDISPATCHCOMPUTEPROC DispatchCompute;
        extern FFW_API PFNGLFRAMEBUFFERPARAMETERIPROC FramebufferParameteri;
        extern FFW_API PFNGLGETDEBUGMESSAGELOGPROC GetDebugMessageLog;
        extern FFW_API PFNGLGETFRAMEBUFFERPARAMETERIVPROC GetFramebufferParameteriv;
        extern FFW_API PFNGLGETINTERNALFORMATI64VPROC GetInternalformati64v;
        extern FFW_API PFNGLGETOBJECTLABELPROC GetObjectLabel;
        extern FFW_API PFNGLGETOBJECTPTRLABELPROC GetObjectPtrLabel;
        extern FFW_API PFNGLGETPROGRAMINTERFACEIVPROC GetProgramInterfaceiv;
        extern FFW_API PFNGLGETPROGRAMRESOURCEINDEXPROC GetProgramResourceIndex;
        extern FFW_API PFNGLGETPROGRAMRESOURCEIVPROC GetProgramResourceiv;
        extern FFW_API PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC GetProgramResourceLocationIndex;
        extern FFW_API PFNGLGETPROGRAMRESOURCELOCATIONPROC GetProgramResourceLocation;
        extern FFW_API PFNGLGETPROGRAMRESOURCENAMEPROC GetProgramResourceName;
        extern FFW_API PFNGLINVALIDATEBUFFERDATAPROC InvalidateBufferData;
        extern FFW_API PFNGLINVALIDATEBUFFERSUBDATAPROC InvalidateBufferSubData;
        extern FFW_API PFNGLINVALIDATEFRAMEBUFFERPROC InvalidateFramebuffer;
        extern FFW_API PFNGLINVALIDATESUBFRAMEBUFFERPROC InvalidateSubFramebuffer;
        extern FFW_API PFNGLINVALIDATETEXIMAGEPROC InvalidateTexImage;
        extern FFW_API PFNGLINVALIDATETEXSUBIMAGEPROC InvalidateTexSubImage;
        extern FFW_API PFNGLMULTIDRAWARRAYSINDIRECTPROC MultiDrawArraysIndirect;
        extern FFW_API PFNGLMULTIDRAWELEMENTSINDIRECTPROC MultiDrawElementsIndirect;
        extern FFW_API PFNGLOBJECTLABELPROC ObjectLabel;
        extern FFW_API PFNGLOBJECTPTRLABELPROC ObjectPtrLabel;
        extern FFW_API PFNGLPOPDEBUGGROUPPROC PopDebugGroup;
        extern FFW_API PFNGLPUSHDEBUGGROUPPROC PushDebugGroup;
        extern FFW_API PFNGLSHADERSTORAGEBLOCKBINDINGPROC ShaderStorageBlockBinding;
        extern FFW_API PFNGLTEXBUFFERRANGEPROC TexBufferRange;
        extern FFW_API PFNGLTEXSTORAGE2DMULTISAMPLEPROC TexStorage2DMultisample;
        extern FFW_API PFNGLTEXSTORAGE3DMULTISAMPLEPROC TexStorage3DMultisample;
        extern FFW_API PFNGLTEXTUREVIEWPROC TextureView;
        extern FFW_API PFNGLVERTEXATTRIBBINDINGPROC VertexAttribBinding;
        extern FFW_API PFNGLVERTEXATTRIBFORMATPROC VertexAttribFormat;
        extern FFW_API PFNGLVERTEXATTRIBIFORMATPROC VertexAttribIFormat;
        extern FFW_API PFNGLVERTEXATTRIBLFORMATPROC VertexAttribLFormat;
        extern FFW_API PFNGLVERTEXBINDINGDIVISORPROC VertexBindingDivisor;
#endif /* GL_VERSION_4_3 */

#ifdef GL_VERSION_4_4
        extern FFW_API PFNGLBINDBUFFERSBASEPROC BindBuffersBase;
        extern FFW_API PFNGLBINDBUFFERSRANGEPROC BindBuffersRange;
        extern FFW_API PFNGLBINDIMAGETEXTURESPROC BindImageTextures;
        extern FFW_API PFNGLBINDSAMPLERSPROC BindSamplers;
        extern FFW_API PFNGLBINDTEXTURESPROC BindTextures;
        extern FFW_API PFNGLBINDVERTEXBUFFERSPROC BindVertexBuffers;
        extern FFW_API PFNGLBUFFERSTORAGEPROC BufferStorage;
        extern FFW_API PFNGLCLEARTEXIMAGEPROC ClearTexImage;
        extern FFW_API PFNGLCLEARTEXSUBIMAGEPROC ClearTexSubImage;
#endif /* GL_VERSION_4_4 */

#ifdef GL_VERSION_4_5
        extern FFW_API PFNGLBINDTEXTUREUNITPROC BindTextureUnit;
        extern FFW_API PFNGLBLITNAMEDFRAMEBUFFERPROC BlitNamedFramebuffer;
        extern FFW_API PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC CheckNamedFramebufferStatus;
        extern FFW_API PFNGLCLEARNAMEDBUFFERDATAPROC ClearNamedBufferData;
        extern FFW_API PFNGLCLEARNAMEDBUFFERSUBDATAPROC ClearNamedBufferSubData;
        extern FFW_API PFNGLCLEARNAMEDFRAMEBUFFERFIPROC ClearNamedFramebufferfi;
        extern FFW_API PFNGLCLEARNAMEDFRAMEBUFFERFVPROC ClearNamedFramebufferfv;
        extern FFW_API PFNGLCLEARNAMEDFRAMEBUFFERIVPROC ClearNamedFramebufferiv;
        extern FFW_API PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC ClearNamedFramebufferuiv;
        extern FFW_API PFNGLCLIPCONTROLPROC ClipControl;
        extern FFW_API PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC CompressedTextureSubImage1D;
        extern FFW_API PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC CompressedTextureSubImage2D;
        extern FFW_API PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC CompressedTextureSubImage3D;
        extern FFW_API PFNGLCOPYNAMEDBUFFERSUBDATAPROC CopyNamedBufferSubData;
        extern FFW_API PFNGLCOPYTEXTURESUBIMAGE1DPROC CopyTextureSubImage1D;
        extern FFW_API PFNGLCOPYTEXTURESUBIMAGE2DPROC CopyTextureSubImage2D;
        extern FFW_API PFNGLCOPYTEXTURESUBIMAGE3DPROC CopyTextureSubImage3D;
        extern FFW_API PFNGLCREATEBUFFERSPROC CreateBuffers;
        extern FFW_API PFNGLCREATEFRAMEBUFFERSPROC CreateFramebuffers;
        extern FFW_API PFNGLCREATEPROGRAMPIPELINESPROC CreateProgramPipelines;
        extern FFW_API PFNGLCREATEQUERIESPROC CreateQueries;
        extern FFW_API PFNGLCREATERENDERBUFFERSPROC CreateRenderbuffers;
        extern FFW_API PFNGLCREATESAMPLERSPROC CreateSamplers;
        extern FFW_API PFNGLCREATETEXTURESPROC CreateTextures;
        extern FFW_API PFNGLCREATETRANSFORMFEEDBACKSPROC CreateTransformFeedbacks;
        extern FFW_API PFNGLCREATEVERTEXARRAYSPROC CreateVertexArrays;
        extern FFW_API PFNGLDISABLEVERTEXARRAYATTRIBPROC DisableVertexArrayAttrib;
        extern FFW_API PFNGLENABLEVERTEXARRAYATTRIBPROC EnableVertexArrayAttrib;
        extern FFW_API PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC FlushMappedNamedBufferRange;
        extern FFW_API PFNGLGENERATETEXTUREMIPMAPPROC GenerateTextureMipmap;
        extern FFW_API PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC GetCompressedTextureImage;
        extern FFW_API PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC GetCompressedTextureSubImage;
        extern FFW_API PFNGLGETGRAPHICSRESETSTATUSPROC GetGraphicsResetStatus;
        extern FFW_API PFNGLGETNAMEDBUFFERPARAMETERI64VPROC GetNamedBufferParameteri64v;
        extern FFW_API PFNGLGETNAMEDBUFFERPARAMETERIVPROC GetNamedBufferParameteriv;
        extern FFW_API PFNGLGETNAMEDBUFFERPOINTERVPROC GetNamedBufferPointerv;
        extern FFW_API PFNGLGETNAMEDBUFFERSUBDATAPROC GetNamedBufferSubData;
        extern FFW_API PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC GetNamedFramebufferAttachmentParameteriv;
        extern FFW_API PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC GetNamedFramebufferParameteriv;
        extern FFW_API PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC GetNamedRenderbufferParameteriv;
        extern FFW_API PFNGLGETNCOMPRESSEDTEXIMAGEPROC GetnCompressedTexImage;
        extern FFW_API PFNGLGETNTEXIMAGEPROC GetnTexImage;
        extern FFW_API PFNGLGETNUNIFORMDVPROC GetnUniformdv;
        extern FFW_API PFNGLGETNUNIFORMFVPROC GetnUniformfv;
        extern FFW_API PFNGLGETNUNIFORMIVPROC GetnUniformiv;
        extern FFW_API PFNGLGETNUNIFORMUIVPROC GetnUniformuiv;
#ifdef FFW_WINDOWS
        extern FFW_API PFNGLGETQUERYBUFFEROBJECTI64VPROC GetQueryBufferObjecti64v;
        extern FFW_API PFNGLGETQUERYBUFFEROBJECTIVPROC GetQueryBufferObjectiv;
        extern FFW_API PFNGLGETQUERYBUFFEROBJECTUI64VPROC GetQueryBufferObjectui64v;
        extern FFW_API PFNGLGETQUERYBUFFEROBJECTUIVPROC GetQueryBufferObjectuiv;
#endif
        extern FFW_API PFNGLGETTEXTUREIMAGEPROC GetTextureImage;
        extern FFW_API PFNGLGETTEXTURELEVELPARAMETERFVPROC GetTextureLevelParameterfv;
        extern FFW_API PFNGLGETTEXTURELEVELPARAMETERIVPROC GetTextureLevelParameteriv;
        extern FFW_API PFNGLGETTEXTUREPARAMETERFVPROC GetTextureParameterfv;
        extern FFW_API PFNGLGETTEXTUREPARAMETERIIVPROC GetTextureParameterIiv;
        extern FFW_API PFNGLGETTEXTUREPARAMETERIUIVPROC GetTextureParameterIuiv;
        extern FFW_API PFNGLGETTEXTUREPARAMETERIVPROC GetTextureParameteriv;
        extern FFW_API PFNGLGETTEXTURESUBIMAGEPROC GetTextureSubImage;
        extern FFW_API PFNGLGETTRANSFORMFEEDBACKI64_VPROC GetTransformFeedbacki64_v;
        extern FFW_API PFNGLGETTRANSFORMFEEDBACKIVPROC GetTransformFeedbackiv;
        extern FFW_API PFNGLGETTRANSFORMFEEDBACKI_VPROC GetTransformFeedbacki_v;
        extern FFW_API PFNGLGETVERTEXARRAYINDEXED64IVPROC GetVertexArrayIndexed64iv;
        extern FFW_API PFNGLGETVERTEXARRAYINDEXEDIVPROC GetVertexArrayIndexediv;
        extern FFW_API PFNGLGETVERTEXARRAYIVPROC GetVertexArrayiv;
        extern FFW_API PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC InvalidateNamedFramebufferData;
        extern FFW_API PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC InvalidateNamedFramebufferSubData;
        extern FFW_API PFNGLMAPNAMEDBUFFERPROC MapNamedBuffer;
        extern FFW_API PFNGLMAPNAMEDBUFFERRANGEPROC MapNamedBufferRange;
        extern FFW_API PFNGLMEMORYBARRIERBYREGIONPROC MemoryBarrierByRegion;
        extern FFW_API PFNGLNAMEDBUFFERDATAPROC NamedBufferData;
        extern FFW_API PFNGLNAMEDBUFFERSTORAGEPROC NamedBufferStorage;
        extern FFW_API PFNGLNAMEDBUFFERSUBDATAPROC NamedBufferSubData;
        extern FFW_API PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC NamedFramebufferDrawBuffer;
        extern FFW_API PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC NamedFramebufferDrawBuffers;
        extern FFW_API PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC NamedFramebufferParameteri;
        extern FFW_API PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC NamedFramebufferReadBuffer;
        extern FFW_API PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC NamedFramebufferRenderbuffer;
        extern FFW_API PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC NamedFramebufferTextureLayer;
        extern FFW_API PFNGLNAMEDFRAMEBUFFERTEXTUREPROC NamedFramebufferTexture;
        extern FFW_API PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC NamedRenderbufferStorageMultisample;
        extern FFW_API PFNGLNAMEDRENDERBUFFERSTORAGEPROC NamedRenderbufferStorage;
        extern FFW_API PFNGLREADNPIXELSPROC ReadnPixels;
        extern FFW_API PFNGLTEXTUREBARRIERPROC TextureBarrier;
        extern FFW_API PFNGLTEXTUREBUFFERPROC TextureBuffer;
        extern FFW_API PFNGLTEXTUREBUFFERRANGEPROC TextureBufferRange;
        extern FFW_API PFNGLTEXTUREPARAMETERFPROC TextureParameterf;
        extern FFW_API PFNGLTEXTUREPARAMETERFVPROC TextureParameterfv;
        extern FFW_API PFNGLTEXTUREPARAMETERIIVPROC TextureParameterIiv;
        extern FFW_API PFNGLTEXTUREPARAMETERIPROC TextureParameteri;
        extern FFW_API PFNGLTEXTUREPARAMETERIUIVPROC TextureParameterIuiv;
        extern FFW_API PFNGLTEXTUREPARAMETERIVPROC TextureParameteriv;
        extern FFW_API PFNGLTEXTURESTORAGE1DPROC TextureStorage1D;
        extern FFW_API PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC TextureStorage2DMultisample;
        extern FFW_API PFNGLTEXTURESTORAGE2DPROC TextureStorage2D;
        extern FFW_API PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC TextureStorage3DMultisample;
        extern FFW_API PFNGLTEXTURESTORAGE3DPROC TextureStorage3D;
        extern FFW_API PFNGLTEXTURESUBIMAGE1DPROC TextureSubImage1D;
        extern FFW_API PFNGLTEXTURESUBIMAGE2DPROC TextureSubImage2D;
        extern FFW_API PFNGLTEXTURESUBIMAGE3DPROC TextureSubImage3D;
        extern FFW_API PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC TransformFeedbackBufferBase;
        extern FFW_API PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC TransformFeedbackBufferRange;
        extern FFW_API PFNGLUNMAPNAMEDBUFFERPROC UnmapNamedBuffer;
        extern FFW_API PFNGLVERTEXARRAYATTRIBBINDINGPROC VertexArrayAttribBinding;
        extern FFW_API PFNGLVERTEXARRAYATTRIBFORMATPROC VertexArrayAttribFormat;
        extern FFW_API PFNGLVERTEXARRAYATTRIBIFORMATPROC VertexArrayAttribIFormat;
        extern FFW_API PFNGLVERTEXARRAYATTRIBLFORMATPROC VertexArrayAttribLFormat;
        extern FFW_API PFNGLVERTEXARRAYBINDINGDIVISORPROC VertexArrayBindingDivisor;
        extern FFW_API PFNGLVERTEXARRAYELEMENTBUFFERPROC VertexArrayElementBuffer;
        extern FFW_API PFNGLVERTEXARRAYVERTEXBUFFERPROC VertexArrayVertexBuffer;
        extern FFW_API PFNGLVERTEXARRAYVERTEXBUFFERSPROC VertexArrayVertexBuffers;
#endif /* GL_VERSION_4_5 */

#ifdef GL_VERSION_4_6
        extern FFW_API PFNGLMULTIDRAWARRAYSINDIRECTCOUNTPROC MultiDrawArraysIndirectCount;
        extern FFW_API PFNGLMULTIDRAWELEMENTSINDIRECTCOUNTPROC MultiDrawElementsIndirectCount;
        extern FFW_API PFNGLPOLYGONOFFSETCLAMPPROC PolygonOffsetClamp;
        extern FFW_API PFNGLSPECIALIZESHADERPROC SpecializeShader;
#endif /* GL_VERSION_4_6 */

    }

    /**
     * @ingroup graphics
     */
    void loadGlCoreArb(void* (*glextLoader)(const char*));
};

#ifdef FFW_WINDOWS
#ifdef FFW_WINGDIAPI_DEFINED
#undef WINGDIAPI
#undef APIENTRY
#endif
#endif

// If you wish not to define the following GL defines, add #define FFW_DO_NOT_EXPORT_GL 1 into your program
#ifndef FFW_DO_NOT_EXPORT_GL_PROC
#ifdef GL_VERSION_1_2
#define glCopyTexSubImage3D ffw::gl::CopyTexSubImage3D
#define glDrawRangeElements ffw::gl::DrawRangeElements
#define glTexImage3D ffw::gl::TexImage3D
#define glTexSubImage3D ffw::gl::TexSubImage3D
#endif /* GL_VERSION_1_2 */

#ifdef GL_VERSION_1_3
#define glActiveTexture ffw::gl::ActiveTexture
#define glCompressedTexImage1D ffw::gl::CompressedTexImage1D
#define glCompressedTexImage2D ffw::gl::CompressedTexImage2D
#define glCompressedTexImage3D ffw::gl::CompressedTexImage3D
#define glCompressedTexSubImage1D ffw::gl::CompressedTexSubImage1D
#define glCompressedTexSubImage2D ffw::gl::CompressedTexSubImage2D
#define glCompressedTexSubImage3D ffw::gl::CompressedTexSubImage3D
#define glGetCompressedTexImage ffw::gl::GetCompressedTexImage
#define glSampleCoverage ffw::gl::SampleCoverage
#endif /* GL_VERSION_1_3 */

#ifdef GL_VERSION_1_4
#define glBlendColor ffw::gl::BlendColor
#define glBlendEquation ffw::gl::BlendEquation
#define glBlendFuncSeparate ffw::gl::BlendFuncSeparate
#define glMultiDrawArrays ffw::gl::MultiDrawArrays
#define glMultiDrawElements ffw::gl::MultiDrawElements
#define glPointParameterf ffw::gl::PointParameterf
#define glPointParameterfv ffw::gl::PointParameterfv
#define glPointParameteri ffw::gl::PointParameteri
#define glPointParameteriv ffw::gl::PointParameteriv
#endif /* GL_VERSION_1_4 */

#ifdef GL_VERSION_1_5
#define glBeginQuery ffw::gl::BeginQuery
#define glBindBuffer ffw::gl::BindBuffer
#define glBufferData ffw::gl::BufferData
#define glBufferSubData ffw::gl::BufferSubData
#define glDeleteBuffers ffw::gl::DeleteBuffers
#define glDeleteQueries ffw::gl::DeleteQueries
#define glEndQuery ffw::gl::EndQuery
#define glGenBuffers ffw::gl::GenBuffers
#define glGenQueries ffw::gl::GenQueries
#define glGetBufferParameteriv ffw::gl::GetBufferParameteriv
#define glGetBufferPointerv ffw::gl::GetBufferPointerv
#define glGetBufferSubData ffw::gl::GetBufferSubData
#define glGetQueryiv ffw::gl::GetQueryiv
#define glGetQueryObjectiv ffw::gl::GetQueryObjectiv
#define glGetQueryObjectuiv ffw::gl::GetQueryObjectuiv
#define glIsBuffer ffw::gl::IsBuffer
#define glIsQuery ffw::gl::IsQuery
#define glMapBuffer ffw::gl::MapBuffer
#define glUnmapBuffer ffw::gl::UnmapBuffer
#endif /* GL_VERSION_1_5 */

#ifdef GL_VERSION_2_0
#define glAttachShader ffw::gl::AttachShader
#define glBindAttribLocation ffw::gl::BindAttribLocation
#define glBlendEquationSeparate ffw::gl::BlendEquationSeparate
#define glCompileShader ffw::gl::CompileShader
#define glCreateProgram ffw::gl::CreateProgram
#define glCreateShader ffw::gl::CreateShader
#define glDeleteProgram ffw::gl::DeleteProgram
#define glDeleteShader ffw::gl::DeleteShader
#define glDetachShader ffw::gl::DetachShader
#define glDisableVertexAttribArray ffw::gl::DisableVertexAttribArray
#define glDrawBuffers ffw::gl::DrawBuffers
#define glEnableVertexAttribArray ffw::gl::EnableVertexAttribArray
#define glGetActiveAttrib ffw::gl::GetActiveAttrib
#define glGetActiveUniform ffw::gl::GetActiveUniform
#define glGetAttachedShaders ffw::gl::GetAttachedShaders
#define glGetAttribLocation ffw::gl::GetAttribLocation
#define glGetProgramInfoLog ffw::gl::GetProgramInfoLog
#define glGetProgramiv ffw::gl::GetProgramiv
#define glGetShaderInfoLog ffw::gl::GetShaderInfoLog
#define glGetShaderiv ffw::gl::GetShaderiv
#define glGetShaderSource ffw::gl::GetShaderSource
#define glGetUniformfv ffw::gl::GetUniformfv
#define glGetUniformiv ffw::gl::GetUniformiv
#define glGetUniformLocation ffw::gl::GetUniformLocation
#define glGetVertexAttribdv ffw::gl::GetVertexAttribdv
#define glGetVertexAttribfv ffw::gl::GetVertexAttribfv
#define glGetVertexAttribiv ffw::gl::GetVertexAttribiv
#define glGetVertexAttribPointerv ffw::gl::GetVertexAttribPointerv
#define glIsProgram ffw::gl::IsProgram
#define glIsShader ffw::gl::IsShader
#define glLinkProgram ffw::gl::LinkProgram
#define glShaderSource ffw::gl::ShaderSource
#define glStencilFuncSeparate ffw::gl::StencilFuncSeparate
#define glStencilMaskSeparate ffw::gl::StencilMaskSeparate
#define glStencilOpSeparate ffw::gl::StencilOpSeparate
#define glUniform1f ffw::gl::Uniform1f
#define glUniform1fv ffw::gl::Uniform1fv
#define glUniform1i ffw::gl::Uniform1i
#define glUniform1iv ffw::gl::Uniform1iv
#define glUniform2f ffw::gl::Uniform2f
#define glUniform2fv ffw::gl::Uniform2fv
#define glUniform2i ffw::gl::Uniform2i
#define glUniform2iv ffw::gl::Uniform2iv
#define glUniform3f ffw::gl::Uniform3f
#define glUniform3fv ffw::gl::Uniform3fv
#define glUniform3i ffw::gl::Uniform3i
#define glUniform3iv ffw::gl::Uniform3iv
#define glUniform4f ffw::gl::Uniform4f
#define glUniform4fv ffw::gl::Uniform4fv
#define glUniform4i ffw::gl::Uniform4i
#define glUniform4iv ffw::gl::Uniform4iv
#define glUniformMatrix2fv ffw::gl::UniformMatrix2fv
#define glUniformMatrix3fv ffw::gl::UniformMatrix3fv
#define glUniformMatrix4fv ffw::gl::UniformMatrix4fv
#define glUseProgram ffw::gl::UseProgram
#define glValidateProgram ffw::gl::ValidateProgram
#define glVertexAttrib1d ffw::gl::VertexAttrib1d
#define glVertexAttrib1dv ffw::gl::VertexAttrib1dv
#define glVertexAttrib1f ffw::gl::VertexAttrib1f
#define glVertexAttrib1fv ffw::gl::VertexAttrib1fv
#define glVertexAttrib1s ffw::gl::VertexAttrib1s
#define glVertexAttrib1sv ffw::gl::VertexAttrib1sv
#define glVertexAttrib2d ffw::gl::VertexAttrib2d
#define glVertexAttrib2dv ffw::gl::VertexAttrib2dv
#define glVertexAttrib2f ffw::gl::VertexAttrib2f
#define glVertexAttrib2fv ffw::gl::VertexAttrib2fv
#define glVertexAttrib2s ffw::gl::VertexAttrib2s
#define glVertexAttrib2sv ffw::gl::VertexAttrib2sv
#define glVertexAttrib3d ffw::gl::VertexAttrib3d
#define glVertexAttrib3dv ffw::gl::VertexAttrib3dv
#define glVertexAttrib3f ffw::gl::VertexAttrib3f
#define glVertexAttrib3fv ffw::gl::VertexAttrib3fv
#define glVertexAttrib3s ffw::gl::VertexAttrib3s
#define glVertexAttrib3sv ffw::gl::VertexAttrib3sv
#define glVertexAttrib4bv ffw::gl::VertexAttrib4bv
#define glVertexAttrib4d ffw::gl::VertexAttrib4d
#define glVertexAttrib4dv ffw::gl::VertexAttrib4dv
#define glVertexAttrib4f ffw::gl::VertexAttrib4f
#define glVertexAttrib4fv ffw::gl::VertexAttrib4fv
#define glVertexAttrib4iv ffw::gl::VertexAttrib4iv
#define glVertexAttrib4Nbv ffw::gl::VertexAttrib4Nbv
#define glVertexAttrib4Niv ffw::gl::VertexAttrib4Niv
#define glVertexAttrib4Nsv ffw::gl::VertexAttrib4Nsv
#define glVertexAttrib4Nub ffw::gl::VertexAttrib4Nub
#define glVertexAttrib4Nubv ffw::gl::VertexAttrib4Nubv
#define glVertexAttrib4Nuiv ffw::gl::VertexAttrib4Nuiv
#define glVertexAttrib4Nusv ffw::gl::VertexAttrib4Nusv
#define glVertexAttrib4s ffw::gl::VertexAttrib4s
#define glVertexAttrib4sv ffw::gl::VertexAttrib4sv
#define glVertexAttrib4ubv ffw::gl::VertexAttrib4ubv
#define glVertexAttrib4uiv ffw::gl::VertexAttrib4uiv
#define glVertexAttrib4usv ffw::gl::VertexAttrib4usv
#define glVertexAttribPointer ffw::gl::VertexAttribPointer
#endif /* GL_VERSION_2_0 */

#ifdef GL_VERSION_2_1
#define glUniformMatrix2x3fv ffw::gl::UniformMatrix2x3fv
#define glUniformMatrix2x4fv ffw::gl::UniformMatrix2x4fv
#define glUniformMatrix3x2fv ffw::gl::UniformMatrix3x2fv
#define glUniformMatrix3x4fv ffw::gl::UniformMatrix3x4fv
#define glUniformMatrix4x2fv ffw::gl::UniformMatrix4x2fv
#define glUniformMatrix4x3fv ffw::gl::UniformMatrix4x3fv
#endif /* GL_VERSION_2_1 */

#ifdef GL_VERSION_3_0
#define glBeginConditionalRender ffw::gl::BeginConditionalRender
#define glBeginTransformFeedback ffw::gl::BeginTransformFeedback
#define glBindBufferBase ffw::gl::BindBufferBase
#define glBindBufferRange ffw::gl::BindBufferRange
#define glBindFragDataLocation ffw::gl::BindFragDataLocation
#define glBindFramebuffer ffw::gl::BindFramebuffer
#define glBindRenderbuffer ffw::gl::BindRenderbuffer
#define glBindVertexArray ffw::gl::BindVertexArray
#define glBlitFramebuffer ffw::gl::BlitFramebuffer
#define glCheckFramebufferStatus ffw::gl::CheckFramebufferStatus
#define glClampColor ffw::gl::ClampColor
#define glClearBufferfi ffw::gl::ClearBufferfi
#define glClearBufferfv ffw::gl::ClearBufferfv
#define glClearBufferiv ffw::gl::ClearBufferiv
#define glClearBufferuiv ffw::gl::ClearBufferuiv
#define glColorMaski ffw::gl::ColorMaski
#define glDeleteFramebuffers ffw::gl::DeleteFramebuffers
#define glDeleteRenderbuffers ffw::gl::DeleteRenderbuffers
#define glDeleteVertexArrays ffw::gl::DeleteVertexArrays
#define glDisablei ffw::gl::Disablei
#define glEnablei ffw::gl::Enablei
#define glEndConditionalRender ffw::gl::EndConditionalRender
#define glEndTransformFeedback ffw::gl::EndTransformFeedback
#define glFlushMappedBufferRange ffw::gl::FlushMappedBufferRange
#define glFramebufferRenderbuffer ffw::gl::FramebufferRenderbuffer
#define glFramebufferTexture1D ffw::gl::FramebufferTexture1D
#define glFramebufferTexture2D ffw::gl::FramebufferTexture2D
#define glFramebufferTexture3D ffw::gl::FramebufferTexture3D
#define glFramebufferTextureLayer ffw::gl::FramebufferTextureLayer
#define glGenerateMipmap ffw::gl::GenerateMipmap
#define glGenFramebuffers ffw::gl::GenFramebuffers
#define glGenRenderbuffers ffw::gl::GenRenderbuffers
#define glGenVertexArrays ffw::gl::GenVertexArrays
#define glGetBooleani_v ffw::gl::GetBooleani_v
#define glGetFragDataLocation ffw::gl::GetFragDataLocation
#define glGetFramebufferAttachmentParameteriv ffw::gl::GetFramebufferAttachmentParameteriv
#define glGetIntegeri_v ffw::gl::GetIntegeri_v
#define glGetRenderbufferParameteriv ffw::gl::GetRenderbufferParameteriv
#define glGetStringi ffw::gl::GetStringi
#define glGetTexParameterIiv ffw::gl::GetTexParameterIiv
#define glGetTexParameterIuiv ffw::gl::GetTexParameterIuiv
#define glGetTransformFeedbackVarying ffw::gl::GetTransformFeedbackVarying
#define glGetUniformuiv ffw::gl::GetUniformuiv
#define glGetVertexAttribIiv ffw::gl::GetVertexAttribIiv
#define glGetVertexAttribIuiv ffw::gl::GetVertexAttribIuiv
#define glIsEnabledi ffw::gl::IsEnabledi
#define glIsFramebuffer ffw::gl::IsFramebuffer
#define glIsRenderbuffer ffw::gl::IsRenderbuffer
#define glIsVertexArray ffw::gl::IsVertexArray
#define glMapBufferRange ffw::gl::MapBufferRange
#define glRenderbufferStorageMultisample ffw::gl::RenderbufferStorageMultisample
#define glRenderbufferStorage ffw::gl::RenderbufferStorage
#define glTexParameterIiv ffw::gl::TexParameterIiv
#define glTexParameterIuiv ffw::gl::TexParameterIuiv
#define glTransformFeedbackVaryings ffw::gl::TransformFeedbackVaryings
#define glUniform1ui ffw::gl::Uniform1ui
#define glUniform1uiv ffw::gl::Uniform1uiv
#define glUniform2ui ffw::gl::Uniform2ui
#define glUniform2uiv ffw::gl::Uniform2uiv
#define glUniform3ui ffw::gl::Uniform3ui
#define glUniform3uiv ffw::gl::Uniform3uiv
#define glUniform4ui ffw::gl::Uniform4ui
#define glUniform4uiv ffw::gl::Uniform4uiv
#define glVertexAttribI1i ffw::gl::VertexAttribI1i
#define glVertexAttribI1iv ffw::gl::VertexAttribI1iv
#define glVertexAttribI1ui ffw::gl::VertexAttribI1ui
#define glVertexAttribI1uiv ffw::gl::VertexAttribI1uiv
#define glVertexAttribI2i ffw::gl::VertexAttribI2i
#define glVertexAttribI2iv ffw::gl::VertexAttribI2iv
#define glVertexAttribI2ui ffw::gl::VertexAttribI2ui
#define glVertexAttribI2uiv ffw::gl::VertexAttribI2uiv
#define glVertexAttribI3i ffw::gl::VertexAttribI3i
#define glVertexAttribI3iv ffw::gl::VertexAttribI3iv
#define glVertexAttribI3ui ffw::gl::VertexAttribI3ui
#define glVertexAttribI3uiv ffw::gl::VertexAttribI3uiv
#define glVertexAttribI4bv ffw::gl::VertexAttribI4bv
#define glVertexAttribI4i ffw::gl::VertexAttribI4i
#define glVertexAttribI4iv ffw::gl::VertexAttribI4iv
#define glVertexAttribI4sv ffw::gl::VertexAttribI4sv
#define glVertexAttribI4ubv ffw::gl::VertexAttribI4ubv
#define glVertexAttribI4ui ffw::gl::VertexAttribI4ui
#define glVertexAttribI4uiv ffw::gl::VertexAttribI4uiv
#define glVertexAttribI4usv ffw::gl::VertexAttribI4usv
#define glVertexAttribIPointer ffw::gl::VertexAttribIPointer
#endif /* GL_VERSION_3_0 */

#ifdef GL_VERSION_3_1
#define glCopyBufferSubData ffw::gl::CopyBufferSubData
#define glDrawArraysInstanced ffw::gl::DrawArraysInstanced
#define glDrawElementsInstanced ffw::gl::DrawElementsInstanced
#define glGetActiveUniformBlockiv ffw::gl::GetActiveUniformBlockiv
#define glGetActiveUniformBlockName ffw::gl::GetActiveUniformBlockName
#define glGetActiveUniformName ffw::gl::GetActiveUniformName
#define glGetActiveUniformsiv ffw::gl::GetActiveUniformsiv
#define glGetUniformBlockIndex ffw::gl::GetUniformBlockIndex
#define glGetUniformIndices ffw::gl::GetUniformIndices
#define glPrimitiveRestartIndex ffw::gl::PrimitiveRestartIndex
#define glTexBuffer ffw::gl::TexBuffer
#define glUniformBlockBinding ffw::gl::UniformBlockBinding
#endif /* GL_VERSION_3_1 */

#ifdef GL_VERSION_3_2
#define glClientWaitSync ffw::gl::ClientWaitSync
#define glDeleteSync ffw::gl::DeleteSync
#define glDrawElementsBaseVertex ffw::gl::DrawElementsBaseVertex
#define glDrawElementsInstancedBaseVertex ffw::gl::DrawElementsInstancedBaseVertex
#define glDrawRangeElementsBaseVertex ffw::gl::DrawRangeElementsBaseVertex
#define glFenceSync ffw::gl::FenceSync
#define glFramebufferTexture ffw::gl::FramebufferTexture
#define glGetBufferParameteri64v ffw::gl::GetBufferParameteri64v
#define glGetInteger64i_v ffw::gl::GetInteger64i_v
#define glGetInteger64v ffw::gl::GetInteger64v
#define glGetMultisamplefv ffw::gl::GetMultisamplefv
#define glGetSynciv ffw::gl::GetSynciv
#define glIsSync ffw::gl::IsSync
#define glMultiDrawElementsBaseVertex ffw::gl::MultiDrawElementsBaseVertex
#define glProvokingVertex ffw::gl::ProvokingVertex
#define glSampleMaski ffw::gl::SampleMaski
#define glTexImage2DMultisample ffw::gl::TexImage2DMultisample
#define glTexImage3DMultisample ffw::gl::TexImage3DMultisample
#define glWaitSync ffw::gl::WaitSync
#endif /* GL_VERSION_3_2 */

#ifdef GL_VERSION_3_3
#define glBindFragDataLocationIndexed ffw::gl::BindFragDataLocationIndexed
#define glBindSampler ffw::gl::BindSampler
#define glDeleteSamplers ffw::gl::DeleteSamplers
#define glGenSamplers ffw::gl::GenSamplers
#define glGetFragDataIndex ffw::gl::GetFragDataIndex
#define glGetQueryObjecti64v ffw::gl::GetQueryObjecti64v
#define glGetQueryObjectui64v ffw::gl::GetQueryObjectui64v
#define glGetSamplerParameterfv ffw::gl::GetSamplerParameterfv
#define glGetSamplerParameterIiv ffw::gl::GetSamplerParameterIiv
#define glGetSamplerParameterIuiv ffw::gl::GetSamplerParameterIuiv
#define glGetSamplerParameteriv ffw::gl::GetSamplerParameteriv
#define glIsSampler ffw::gl::IsSampler
#define glQueryCounter ffw::gl::QueryCounter
#define glSamplerParameterf ffw::gl::SamplerParameterf
#define glSamplerParameterfv ffw::gl::SamplerParameterfv
#define glSamplerParameterIiv ffw::gl::SamplerParameterIiv
#define glSamplerParameteri ffw::gl::SamplerParameteri
#define glSamplerParameterIuiv ffw::gl::SamplerParameterIuiv
#define glSamplerParameteriv ffw::gl::SamplerParameteriv
#define glVertexAttribDivisor ffw::gl::VertexAttribDivisor
#define glVertexAttribP1ui ffw::gl::VertexAttribP1ui
#define glVertexAttribP1uiv ffw::gl::VertexAttribP1uiv
#define glVertexAttribP2ui ffw::gl::VertexAttribP2ui
#define glVertexAttribP2uiv ffw::gl::VertexAttribP2uiv
#define glVertexAttribP3ui ffw::gl::VertexAttribP3ui
#define glVertexAttribP3uiv ffw::gl::VertexAttribP3uiv
#define glVertexAttribP4ui ffw::gl::VertexAttribP4ui
#define glVertexAttribP4uiv ffw::gl::VertexAttribP4uiv
#endif /* GL_VERSION_3_3 */

#ifdef GL_VERSION_4_0
#define glBeginQueryIndexed ffw::gl::BeginQueryIndexed
#define glBindTransformFeedback ffw::gl::BindTransformFeedback
#define glBlendEquationi ffw::gl::BlendEquationi
#define glBlendEquationSeparatei ffw::gl::BlendEquationSeparatei
#define glBlendFunci ffw::gl::BlendFunci
#define glBlendFuncSeparatei ffw::gl::BlendFuncSeparatei
#define glDeleteTransformFeedbacks ffw::gl::DeleteTransformFeedbacks
#define glDrawArraysIndirect ffw::gl::DrawArraysIndirect
#define glDrawElementsIndirect ffw::gl::DrawElementsIndirect
#define glDrawTransformFeedback ffw::gl::DrawTransformFeedback
#define glDrawTransformFeedbackStream ffw::gl::DrawTransformFeedbackStream
#define glEndQueryIndexed ffw::gl::EndQueryIndexed
#define glGenTransformFeedbacks ffw::gl::GenTransformFeedbacks
#define glGetActiveSubroutineName ffw::gl::GetActiveSubroutineName
#define glGetActiveSubroutineUniformiv ffw::gl::GetActiveSubroutineUniformiv
#define glGetActiveSubroutineUniformName ffw::gl::GetActiveSubroutineUniformName
#define glGetProgramStageiv ffw::gl::GetProgramStageiv
#define glGetQueryIndexediv ffw::gl::GetQueryIndexediv
#define glGetSubroutineIndex ffw::gl::GetSubroutineIndex
#define glGetSubroutineUniformLocation ffw::gl::GetSubroutineUniformLocation
#define glGetUniformdv ffw::gl::GetUniformdv
#define glGetUniformSubroutineuiv ffw::gl::GetUniformSubroutineuiv
#define glIsTransformFeedback ffw::gl::IsTransformFeedback
#define glMinSampleShading ffw::gl::MinSampleShading
#define glPatchParameterfv ffw::gl::PatchParameterfv
#define glPatchParameteri ffw::gl::PatchParameteri
#define glPauseTransformFeedback ffw::gl::PauseTransformFeedback
#define glResumeTransformFeedback ffw::gl::ResumeTransformFeedback
#define glUniform1d ffw::gl::Uniform1d
#define glUniform1dv ffw::gl::Uniform1dv
#define glUniform2d ffw::gl::Uniform2d
#define glUniform2dv ffw::gl::Uniform2dv
#define glUniform3d ffw::gl::Uniform3d
#define glUniform3dv ffw::gl::Uniform3dv
#define glUniform4d ffw::gl::Uniform4d
#define glUniform4dv ffw::gl::Uniform4dv
#define glUniformMatrix2dv ffw::gl::UniformMatrix2dv
#define glUniformMatrix2x3dv ffw::gl::UniformMatrix2x3dv
#define glUniformMatrix2x4dv ffw::gl::UniformMatrix2x4dv
#define glUniformMatrix3dv ffw::gl::UniformMatrix3dv
#define glUniformMatrix3x2dv ffw::gl::UniformMatrix3x2dv
#define glUniformMatrix3x4dv ffw::gl::UniformMatrix3x4dv
#define glUniformMatrix4dv ffw::gl::UniformMatrix4dv
#define glUniformMatrix4x2dv ffw::gl::UniformMatrix4x2dv
#define glUniformMatrix4x3dv ffw::gl::UniformMatrix4x3dv
#define glUniformSubroutinesuiv ffw::gl::UniformSubroutinesuiv
#endif /* GL_VERSION_4_0 */

#ifdef GL_VERSION_4_1
#define glActiveShaderProgram ffw::gl::ActiveShaderProgram
#define glBindProgramPipeline ffw::gl::BindProgramPipeline
#define glClearDepthf ffw::gl::ClearDepthf
#define glCreateShaderProgramv ffw::gl::CreateShaderProgramv
#define glDeleteProgramPipelines ffw::gl::DeleteProgramPipelines
#define glDepthRangeArrayv ffw::gl::DepthRangeArrayv
#define glDepthRangef ffw::gl::DepthRangef
#define glDepthRangeIndexed ffw::gl::DepthRangeIndexed
#define glGenProgramPipelines ffw::gl::GenProgramPipelines
#define glGetDoublei_v ffw::gl::GetDoublei_v
#define glGetFloati_v ffw::gl::GetFloati_v
#define glGetProgramBinary ffw::gl::GetProgramBinary
#define glGetProgramPipelineInfoLog ffw::gl::GetProgramPipelineInfoLog
#define glGetProgramPipelineiv ffw::gl::GetProgramPipelineiv
#define glGetShaderPrecisionFormat ffw::gl::GetShaderPrecisionFormat
#define glGetVertexAttribLdv ffw::gl::GetVertexAttribLdv
#define glIsProgramPipeline ffw::gl::IsProgramPipeline
#define glProgramBinary ffw::gl::ProgramBinary
#define glProgramParameteri ffw::gl::ProgramParameteri
#define glProgramUniform1d ffw::gl::ProgramUniform1d
#define glProgramUniform1dv ffw::gl::ProgramUniform1dv
#define glProgramUniform1f ffw::gl::ProgramUniform1f
#define glProgramUniform1fv ffw::gl::ProgramUniform1fv
#define glProgramUniform1i ffw::gl::ProgramUniform1i
#define glProgramUniform1iv ffw::gl::ProgramUniform1iv
#define glProgramUniform1ui ffw::gl::ProgramUniform1ui
#define glProgramUniform1uiv ffw::gl::ProgramUniform1uiv
#define glProgramUniform2d ffw::gl::ProgramUniform2d
#define glProgramUniform2dv ffw::gl::ProgramUniform2dv
#define glProgramUniform2f ffw::gl::ProgramUniform2f
#define glProgramUniform2fv ffw::gl::ProgramUniform2fv
#define glProgramUniform2i ffw::gl::ProgramUniform2i
#define glProgramUniform2iv ffw::gl::ProgramUniform2iv
#define glProgramUniform2ui ffw::gl::ProgramUniform2ui
#define glProgramUniform2uiv ffw::gl::ProgramUniform2uiv
#define glProgramUniform3d ffw::gl::ProgramUniform3d
#define glProgramUniform3dv ffw::gl::ProgramUniform3dv
#define glProgramUniform3f ffw::gl::ProgramUniform3f
#define glProgramUniform3fv ffw::gl::ProgramUniform3fv
#define glProgramUniform3i ffw::gl::ProgramUniform3i
#define glProgramUniform3iv ffw::gl::ProgramUniform3iv
#define glProgramUniform3ui ffw::gl::ProgramUniform3ui
#define glProgramUniform3uiv ffw::gl::ProgramUniform3uiv
#define glProgramUniform4d ffw::gl::ProgramUniform4d
#define glProgramUniform4dv ffw::gl::ProgramUniform4dv
#define glProgramUniform4f ffw::gl::ProgramUniform4f
#define glProgramUniform4fv ffw::gl::ProgramUniform4fv
#define glProgramUniform4i ffw::gl::ProgramUniform4i
#define glProgramUniform4iv ffw::gl::ProgramUniform4iv
#define glProgramUniform4ui ffw::gl::ProgramUniform4ui
#define glProgramUniform4uiv ffw::gl::ProgramUniform4uiv
#define glProgramUniformMatrix2dv ffw::gl::ProgramUniformMatrix2dv
#define glProgramUniformMatrix2fv ffw::gl::ProgramUniformMatrix2fv
#define glProgramUniformMatrix2x3dv ffw::gl::ProgramUniformMatrix2x3dv
#define glProgramUniformMatrix2x3fv ffw::gl::ProgramUniformMatrix2x3fv
#define glProgramUniformMatrix2x4dv ffw::gl::ProgramUniformMatrix2x4dv
#define glProgramUniformMatrix2x4fv ffw::gl::ProgramUniformMatrix2x4fv
#define glProgramUniformMatrix3dv ffw::gl::ProgramUniformMatrix3dv
#define glProgramUniformMatrix3fv ffw::gl::ProgramUniformMatrix3fv
#define glProgramUniformMatrix3x2dv ffw::gl::ProgramUniformMatrix3x2dv
#define glProgramUniformMatrix3x2fv ffw::gl::ProgramUniformMatrix3x2fv
#define glProgramUniformMatrix3x4dv ffw::gl::ProgramUniformMatrix3x4dv
#define glProgramUniformMatrix3x4fv ffw::gl::ProgramUniformMatrix3x4fv
#define glProgramUniformMatrix4dv ffw::gl::ProgramUniformMatrix4dv
#define glProgramUniformMatrix4fv ffw::gl::ProgramUniformMatrix4fv
#define glProgramUniformMatrix4x2dv ffw::gl::ProgramUniformMatrix4x2dv
#define glProgramUniformMatrix4x2fv ffw::gl::ProgramUniformMatrix4x2fv
#define glProgramUniformMatrix4x3dv ffw::gl::ProgramUniformMatrix4x3dv
#define glProgramUniformMatrix4x3fv ffw::gl::ProgramUniformMatrix4x3fv
#define glReleaseShaderCompiler ffw::gl::ReleaseShaderCompiler
#define glScissorArrayv ffw::gl::ScissorArrayv
#define glScissorIndexed ffw::gl::ScissorIndexed
#define glScissorIndexedv ffw::gl::ScissorIndexedv
#define glShaderBinary ffw::gl::ShaderBinary
#define glUseProgramStages ffw::gl::UseProgramStages
#define glValidateProgramPipeline ffw::gl::ValidateProgramPipeline
#define glVertexAttribL1d ffw::gl::VertexAttribL1d
#define glVertexAttribL1dv ffw::gl::VertexAttribL1dv
#define glVertexAttribL2d ffw::gl::VertexAttribL2d
#define glVertexAttribL2dv ffw::gl::VertexAttribL2dv
#define glVertexAttribL3d ffw::gl::VertexAttribL3d
#define glVertexAttribL3dv ffw::gl::VertexAttribL3dv
#define glVertexAttribL4d ffw::gl::VertexAttribL4d
#define glVertexAttribL4dv ffw::gl::VertexAttribL4dv
#define glVertexAttribLPointer ffw::gl::VertexAttribLPointer
#define glViewportArrayv ffw::gl::ViewportArrayv
#define glViewportIndexedf ffw::gl::ViewportIndexedf
#define glViewportIndexedfv ffw::gl::ViewportIndexedfv
#endif /* GL_VERSION_4_1 */

#ifdef GL_VERSION_4_2
#define glBindImageTexture ffw::gl::BindImageTexture
#define glDrawArraysInstancedBaseInstance ffw::gl::DrawArraysInstancedBaseInstance
#define glDrawElementsInstancedBaseInstance ffw::gl::DrawElementsInstancedBaseInstance
#define glDrawElementsInstancedBaseVertexBaseInstance ffw::gl::DrawElementsInstancedBaseVertexBaseInstance
#define glDrawTransformFeedbackInstanced ffw::gl::DrawTransformFeedbackInstanced
#define glDrawTransformFeedbackStreamInstanced ffw::gl::DrawTransformFeedbackStreamInstanced
#define glGetActiveAtomicCounterBufferiv ffw::gl::GetActiveAtomicCounterBufferiv
#define glGetInternalformativ ffw::gl::GetInternalformativ
#define glMemoryBarrier ffw::gl::MemoryBarrier
#define glTexStorage1D ffw::gl::TexStorage1D
#define glTexStorage2D ffw::gl::TexStorage2D
#define glTexStorage3D ffw::gl::TexStorage3D
#endif /* GL_VERSION_4_2 */

#ifdef GL_VERSION_4_3
#define glBindVertexBuffer ffw::gl::BindVertexBuffer
#define glClearBufferData ffw::gl::ClearBufferData
#define glClearBufferSubData ffw::gl::ClearBufferSubData
#define glCopyImageSubData ffw::gl::CopyImageSubData
#define glDebugMessageCallback ffw::gl::DebugMessageCallback
#define glDebugMessageControl ffw::gl::DebugMessageControl
#define glDebugMessageInsert ffw::gl::DebugMessageInsert
#define glDispatchComputeIndirect ffw::gl::DispatchComputeIndirect
#define glDispatchCompute ffw::gl::DispatchCompute
#define glFramebufferParameteri ffw::gl::FramebufferParameteri
#define glGetDebugMessageLog ffw::gl::GetDebugMessageLog
#define glGetFramebufferParameteriv ffw::gl::GetFramebufferParameteriv
#define glGetInternalformati64v ffw::gl::GetInternalformati64v
#define glGetObjectLabel ffw::gl::GetObjectLabel
#define glGetObjectPtrLabel ffw::gl::GetObjectPtrLabel
#define glGetProgramInterfaceiv ffw::gl::GetProgramInterfaceiv
#define glGetProgramResourceIndex ffw::gl::GetProgramResourceIndex
#define glGetProgramResourceiv ffw::gl::GetProgramResourceiv
#define glGetProgramResourceLocationIndex ffw::gl::GetProgramResourceLocationIndex
#define glGetProgramResourceLocation ffw::gl::GetProgramResourceLocation
#define glGetProgramResourceName ffw::gl::GetProgramResourceName
#define glInvalidateBufferData ffw::gl::InvalidateBufferData
#define glInvalidateBufferSubData ffw::gl::InvalidateBufferSubData
#define glInvalidateFramebuffer ffw::gl::InvalidateFramebuffer
#define glInvalidateSubFramebuffer ffw::gl::InvalidateSubFramebuffer
#define glInvalidateTexImage ffw::gl::InvalidateTexImage
#define glInvalidateTexSubImage ffw::gl::InvalidateTexSubImage
#define glMultiDrawArraysIndirect ffw::gl::MultiDrawArraysIndirect
#define glMultiDrawElementsIndirect ffw::gl::MultiDrawElementsIndirect
#define glObjectLabel ffw::gl::ObjectLabel
#define glObjectPtrLabel ffw::gl::ObjectPtrLabel
#define glPopDebugGroup ffw::gl::PopDebugGroup
#define glPushDebugGroup ffw::gl::PushDebugGroup
#define glShaderStorageBlockBinding ffw::gl::ShaderStorageBlockBinding
#define glTexBufferRange ffw::gl::TexBufferRange
#define glTexStorage2DMultisample ffw::gl::TexStorage2DMultisample
#define glTexStorage3DMultisample ffw::gl::TexStorage3DMultisample
#define glTextureView ffw::gl::TextureView
#define glVertexAttribBinding ffw::gl::VertexAttribBinding
#define glVertexAttribFormat ffw::gl::VertexAttribFormat
#define glVertexAttribIFormat ffw::gl::VertexAttribIFormat
#define glVertexAttribLFormat ffw::gl::VertexAttribLFormat
#define glVertexBindingDivisor ffw::gl::VertexBindingDivisor
#endif /* GL_VERSION_4_3 */

#ifdef GL_VERSION_4_4
#define glBindBuffersBase ffw::gl::BindBuffersBase
#define glBindBuffersRange ffw::gl::BindBuffersRange
#define glBindImageTextures ffw::gl::BindImageTextures
#define glBindSamplers ffw::gl::BindSamplers
#define glBindTextures ffw::gl::BindTextures
#define glBindVertexBuffers ffw::gl::BindVertexBuffers
#define glBufferStorage ffw::gl::BufferStorage
#define glClearTexImage ffw::gl::ClearTexImage
#define glClearTexSubImage ffw::gl::ClearTexSubImage
#endif /* GL_VERSION_4_4 */

#ifdef GL_VERSION_4_5
#define glBindTextureUnit ffw::gl::BindTextureUnit
#define glBlitNamedFramebuffer ffw::gl::BlitNamedFramebuffer
#define glCheckNamedFramebufferStatus ffw::gl::CheckNamedFramebufferStatus
#define glClearNamedBufferData ffw::gl::ClearNamedBufferData
#define glClearNamedBufferSubData ffw::gl::ClearNamedBufferSubData
#define glClearNamedFramebufferfi ffw::gl::ClearNamedFramebufferfi
#define glClearNamedFramebufferfv ffw::gl::ClearNamedFramebufferfv
#define glClearNamedFramebufferiv ffw::gl::ClearNamedFramebufferiv
#define glClearNamedFramebufferuiv ffw::gl::ClearNamedFramebufferuiv
#define glClipControl ffw::gl::ClipControl
#define glCompressedTextureSubImage1D ffw::gl::CompressedTextureSubImage1D
#define glCompressedTextureSubImage2D ffw::gl::CompressedTextureSubImage2D
#define glCompressedTextureSubImage3D ffw::gl::CompressedTextureSubImage3D
#define glCopyNamedBufferSubData ffw::gl::CopyNamedBufferSubData
#define glCopyTextureSubImage1D ffw::gl::CopyTextureSubImage1D
#define glCopyTextureSubImage2D ffw::gl::CopyTextureSubImage2D
#define glCopyTextureSubImage3D ffw::gl::CopyTextureSubImage3D
#define glCreateBuffers ffw::gl::CreateBuffers
#define glCreateFramebuffers ffw::gl::CreateFramebuffers
#define glCreateProgramPipelines ffw::gl::CreateProgramPipelines
#define glCreateQueries ffw::gl::CreateQueries
#define glCreateRenderbuffers ffw::gl::CreateRenderbuffers
#define glCreateSamplers ffw::gl::CreateSamplers
#define glCreateTextures ffw::gl::CreateTextures
#define glCreateTransformFeedbacks ffw::gl::CreateTransformFeedbacks
#define glCreateVertexArrays ffw::gl::CreateVertexArrays
#define glDisableVertexArrayAttrib ffw::gl::DisableVertexArrayAttrib
#define glEnableVertexArrayAttrib ffw::gl::EnableVertexArrayAttrib
#define glFlushMappedNamedBufferRange ffw::gl::FlushMappedNamedBufferRange
#define glGenerateTextureMipmap ffw::gl::GenerateTextureMipmap
#define glGetCompressedTextureImage ffw::gl::GetCompressedTextureImage
#define glGetCompressedTextureSubImage ffw::gl::GetCompressedTextureSubImage
#define glGetGraphicsResetStatus ffw::gl::GetGraphicsResetStatus
#define glGetNamedBufferParameteri64v ffw::gl::GetNamedBufferParameteri64v
#define glGetNamedBufferParameteriv ffw::gl::GetNamedBufferParameteriv
#define glGetNamedBufferPointerv ffw::gl::GetNamedBufferPointerv
#define glGetNamedBufferSubData ffw::gl::GetNamedBufferSubData
#define glGetNamedFramebufferAttachmentParameteriv ffw::gl::GetNamedFramebufferAttachmentParameteriv
#define glGetNamedFramebufferParameteriv ffw::gl::GetNamedFramebufferParameteriv
#define glGetNamedRenderbufferParameteriv ffw::gl::GetNamedRenderbufferParameteriv
#define glGetnCompressedTexImage ffw::gl::GetnCompressedTexImage
#define glGetnTexImage ffw::gl::GetnTexImage
#define glGetnUniformdv ffw::gl::GetnUniformdv
#define glGetnUniformfv ffw::gl::GetnUniformfv
#define glGetnUniformiv ffw::gl::GetnUniformiv
#define glGetnUniformuiv ffw::gl::GetnUniformuiv
#define glGetQueryBufferObjecti64v ffw::gl::GetQueryBufferObjecti64v
#define glGetQueryBufferObjectiv ffw::gl::GetQueryBufferObjectiv
#define glGetQueryBufferObjectui64v ffw::gl::GetQueryBufferObjectui64v
#define glGetQueryBufferObjectuiv ffw::gl::GetQueryBufferObjectuiv
#define glGetTextureImage ffw::gl::GetTextureImage
#define glGetTextureLevelParameterfv ffw::gl::GetTextureLevelParameterfv
#define glGetTextureLevelParameteriv ffw::gl::GetTextureLevelParameteriv
#define glGetTextureParameterfv ffw::gl::GetTextureParameterfv
#define glGetTextureParameterIiv ffw::gl::GetTextureParameterIiv
#define glGetTextureParameterIuiv ffw::gl::GetTextureParameterIuiv
#define glGetTextureParameteriv ffw::gl::GetTextureParameteriv
#define glGetTextureSubImage ffw::gl::GetTextureSubImage
#define glGetTransformFeedbacki64_v ffw::gl::GetTransformFeedbacki64_v
#define glGetTransformFeedbackiv ffw::gl::GetTransformFeedbackiv
#define glGetTransformFeedbacki_v ffw::gl::GetTransformFeedbacki_v
#define glGetVertexArrayIndexed64iv ffw::gl::GetVertexArrayIndexed64iv
#define glGetVertexArrayIndexediv ffw::gl::GetVertexArrayIndexediv
#define glGetVertexArrayiv ffw::gl::GetVertexArrayiv
#define glInvalidateNamedFramebufferData ffw::gl::InvalidateNamedFramebufferData
#define glInvalidateNamedFramebufferSubData ffw::gl::InvalidateNamedFramebufferSubData
#define glMapNamedBuffer ffw::gl::MapNamedBuffer
#define glMapNamedBufferRange ffw::gl::MapNamedBufferRange
#define glMemoryBarrierByRegion ffw::gl::MemoryBarrierByRegion
#define glNamedBufferData ffw::gl::NamedBufferData
#define glNamedBufferStorage ffw::gl::NamedBufferStorage
#define glNamedBufferSubData ffw::gl::NamedBufferSubData
#define glNamedFramebufferDrawBuffer ffw::gl::NamedFramebufferDrawBuffer
#define glNamedFramebufferDrawBuffers ffw::gl::NamedFramebufferDrawBuffers
#define glNamedFramebufferParameteri ffw::gl::NamedFramebufferParameteri
#define glNamedFramebufferReadBuffer ffw::gl::NamedFramebufferReadBuffer
#define glNamedFramebufferRenderbuffer ffw::gl::NamedFramebufferRenderbuffer
#define glNamedFramebufferTextureLayer ffw::gl::NamedFramebufferTextureLayer
#define glNamedFramebufferTexture ffw::gl::NamedFramebufferTexture
#define glNamedRenderbufferStorageMultisample ffw::gl::NamedRenderbufferStorageMultisample
#define glNamedRenderbufferStorage ffw::gl::NamedRenderbufferStorage
#define glReadnPixels ffw::gl::ReadnPixels
#define glTextureBarrier ffw::gl::TextureBarrier
#define glTextureBuffer ffw::gl::TextureBuffer
#define glTextureBufferRange ffw::gl::TextureBufferRange
#define glTextureParameterf ffw::gl::TextureParameterf
#define glTextureParameterfv ffw::gl::TextureParameterfv
#define glTextureParameterIiv ffw::gl::TextureParameterIiv
#define glTextureParameteri ffw::gl::TextureParameteri
#define glTextureParameterIuiv ffw::gl::TextureParameterIuiv
#define glTextureParameteriv ffw::gl::TextureParameteriv
#define glTextureStorage1D ffw::gl::TextureStorage1D
#define glTextureStorage2DMultisample ffw::gl::TextureStorage2DMultisample
#define glTextureStorage2D ffw::gl::TextureStorage2D
#define glTextureStorage3DMultisample ffw::gl::TextureStorage3DMultisample
#define glTextureStorage3D ffw::gl::TextureStorage3D
#define glTextureSubImage1D ffw::gl::TextureSubImage1D
#define glTextureSubImage2D ffw::gl::TextureSubImage2D
#define glTextureSubImage3D ffw::gl::TextureSubImage3D
#define glTransformFeedbackBufferBase ffw::gl::TransformFeedbackBufferBase
#define glTransformFeedbackBufferRange ffw::gl::TransformFeedbackBufferRange
#define glUnmapNamedBuffer ffw::gl::UnmapNamedBuffer
#define glVertexArrayAttribBinding ffw::gl::VertexArrayAttribBinding
#define glVertexArrayAttribFormat ffw::gl::VertexArrayAttribFormat
#define glVertexArrayAttribIFormat ffw::gl::VertexArrayAttribIFormat
#define glVertexArrayAttribLFormat ffw::gl::VertexArrayAttribLFormat
#define glVertexArrayBindingDivisor ffw::gl::VertexArrayBindingDivisor
#define glVertexArrayElementBuffer ffw::gl::VertexArrayElementBuffer
#define glVertexArrayVertexBuffer ffw::gl::VertexArrayVertexBuffer
#define glVertexArrayVertexBuffers ffw::gl::VertexArrayVertexBuffers
#endif /* GL_VERSION_4_5 */

#ifdef GL_VERSION_4_6
#define glMultiDrawArraysIndirectCount ffw::gl::MultiDrawArraysIndirectCount
#define glMultiDrawElementsIndirectCount ffw::gl::MultiDrawElementsIndirectCount
#define glPolygonOffsetClamp ffw::gl::PolygonOffsetClamp
#define glSpecializeShader ffw::gl::SpecializeShader
#endif /* GL_VERSION_4_6 */
#endif

#endif